package info.bliki.wiki.test.big;

import info.bliki.wiki.filter.FilterTestSupport;
import junit.framework.Test;
import junit.framework.TestSuite;

public class BigRenderTest extends FilterTestSupport {
	public final static String TEST1 = "{{alert|content=Note that some Mediawiki syntax is still not implemented by JAMWiki - see the [[Roadmap]] for details.  Please add a comment to the [[Feedback]] page if you come across any syntax in JAMWiki that appears to be broken or if you feel that implementation of a particular Mediawiki syntax element should be given priority in development.}}\r\n"
			+ "\r\n"
			+ "This article is licensed under the [http://www.gnu.org/copyleft/fdl.html GNU Free Documentation License]. It is taken from http://meta.wikimedia.org/wiki/Help:Editing.\r\n"
			+ "\r\n"
			+ "This Editing Overview has a lot of \'\'\'wikitext\'\'\' examples. You may want to keep this page open in a separate browser window for reference while you edit.\r\n"
			+ "Each of the topics covered here is covered somewhere else in more detail. See box at right for that.\r\n"
			+ "\r\n"
			+ "== Editing  basics ==\r\n"
			+ "\r\n"
			+ ";Start editing\r\n"
			+ ":To start editing a MediaWiki page, click the \'\'\'Edit this page\'\'\' (or just \'\'\'edit\'\'\') link at one of its edges. This brings you to the \'\'\'edit page\'\'\': a page with a text box containing the \'\'wikitext\'\': the editable source code from which the server produces the webpage. \'\'If you just want to experiment, please do so in the [[Sandbox|sandbox]], not here\'\'.\r\n"
			+ "\r\n"
			+ ";Type your changes\r\n"
			+ ":You can just type your text. However, also using basic wiki markup (described in the next section) to make links and do simple formatting adds to the value of your contribution.\r\n"
			+ "\r\n"
			+ ";Summarize your changes\r\n"
			+ ":Write a short edit summary in the small field below the edit-box. You may use shorthand to describe your changes, as described in the legend.\r\n"
			+ "\r\n"
			+ ";Preview before saving\r\n"
			+ ":When you have finished, click \'\'\'Show preview\'\'\' to see how your changes will look -- \'\'\'before\'\'\' you make them permanent.  Repeat the edit/preview process until you are satisfied, then click \'\'\'Save page\'\'\' and your changes will be immediately applied to the article.\r\n"
			+ "\r\n"
			+ "=== Basic text formatting ===\r\n"
			+ "\r\n"
			+ "{| width=\"100%\" border=\"1\" cellpadding=\"2\" cellspacing=\"0\"\r\n"
			+ "|-\r\n"
			+ "!What it looks like\r\n"
			+ "!What you type\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "You can \'\'italicize text\'\' by putting 2 \r\n"
			+ "apostrophes on each side. \r\n"
			+ "\r\n"
			+ "3 apostrophes will bold \'\'\'the text\'\'\'. \r\n"
			+ "\r\n"
			+ "5 apostrophes will bold and italicize \r\n"
			+ "\'\'\'\'\'the text\'\'\'\'\'.\r\n"
			+ "\r\n"
			+ "(4 apostrophes don\'t do anything special -- there\'s just \'\'\'\'one left over\'\'\'\'.)\r\n"
			+ "|<pre>\r\n"
			+ "You can \'\'italicize text\'\' by putting 2 \r\n"
			+ "apostrophes on each side. \r\n"
			+ "\r\n"
			+ "3 apostrophes will bold \'\'\'the text\'\'\'. \r\n"
			+ "\r\n"
			+ "5 apostrophes will bold and italicize \r\n"
			+ "\'\'\'\'\'the text\'\'\'\'\'.\r\n"
			+ "\r\n"
			+ "(4 apostrophes don\'t do anything special -- there\'s just \'\'\'\'one left over\'\'\'\'.)\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "A single newline\r\n"
			+ "has no effect\r\n"
			+ "on the layout.\r\n"
			+ "But an empty line\r\n"
			+ "\r\n"
			+ "starts a new paragraph.\r\n"
			+ "|<pre>\r\n"
			+ "A single newline\r\n"
			+ "has no effect\r\n"
			+ "on the layout.\r\n"
			+ "But an empty line\r\n"
			+ "\r\n"
			+ "starts a new paragraph.\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "You can break lines<br>\r\n"
			+ "without a new paragraph.<br>\r\n"
			+ "Please use this sparingly.\r\n"
			+ "|<pre>\r\n"
			+ "You can break lines<br>\r\n"
			+ "without a new paragraph.<br>\r\n"
			+ "Please use this sparingly.\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "You should \"sign\" your comments on talk pages: <br>\r\n"
			+ "- Three tildes gives your user name: [[User:Karl Wick|Karl Wick]] <br>\r\n"
			+ "- Four tildes give your user name plus date/time: [[User:Karl Wick|Karl Wick]] 07:46, 27 November 2005 (UTC) <br>\r\n"
			+ "- Five tildes gives the date/time alone: 07:46, 27 November 2005 (UTC) <br>\r\n"
			+ "|<pre>\r\n"
			+ "You should \"sign\" your comments \r\n"
			+ "on talk pages: <br>\r\n"
			+ "- Three tildes gives your user\r\n"
			+ "name: ~~~ <br>\r\n"
			+ "- Four tildes give your user \r\n"
			+ "name plus date/time: ~~~~ <br>\r\n"
			+ "- Five tildes gives the \r\n"
			+ "date/time alone: ~~~~~ <br>\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "You can use <b>HTML tags</b>, too, if you\r\n"
			+ "want. Some useful ways to use HTML:\r\n"
			+ "\r\n"
			+ "Put text in a <tt>typewriter font</tt>. The same\r\n"
			+ "font is generally used for <code>computer code</code>.\r\n"
			+ "\r\n"
			+ "<strike>Strike out</strike> or <u>underline</u>text,\r\n"
			+ "or write it <span style=\"font-variant:small-caps\">\r\n"
			+ "in small caps</span>.\r\n"
			+ "\r\n"
			+ "Superscripts and subscripts:\r\n"
			+ "X<sup>2</sup>, H<sub>2</sub>O\r\n"
			+ "\r\n"
			+ "Invisible comments to editors ( <!-- --> ) only appear while editing the page.\r\n"
			+ "<!-- Note to editors: blah blah blah. -->\r\n"
			+ "\r\n"
			+ "If you wish to make comments to the public, you should usually go on the [[talk page]], though.\r\n"
			+ "|<pre>\r\n"
			+ "You can use <b>HTML tags</b>,\r\n"
			+ "too, if you want. Some useful\r\n"
			+ "ways to use HTML:\r\n"
			+ "\r\n"
			+ "Put text in a <tt>typewriter\r\n"
			+ "font</tt>. The same font is \r\n"
			+ "generally used for <code>\r\n"
			+ "computer code</code>.\r\n"
			+ "\r\n"
			+ "<strike>Strike out</strike>\r\n"
			+ "or <u>underline</u> text,\r\n"
			+ "or write it <span style=\r\n"
			+ "\"font-variant:small-caps\">\r\n"
			+ "in small caps</span>.\r\n"
			+ "\r\n"
			+ "Superscripts and subscripts:\r\n"
			+ "X<sup>2</sup>, H<sub>2</sub>O\r\n"
			+ "\r\n"
			+ "Invisible comments to editors ( <!-- --> ) \r\n"
			+ "only appear while editing the page.\r\n"
			+ "<!-- Note to editors: blah blah blah. -->\r\n"
			+ "\r\n"
			+ "If you wish to make comments to the public, \r\n"
			+ "you should usually go on the talk page, though.\r\n"
			+ "</pre>\r\n"
			+ "|}\r\n"
			+ "\r\n"
			+ "In general you should avoid HTML in favor of Wiki markup whenever possible.\r\n"
			+ "\r\n"
			+ "=== Organizing your writing ===\r\n"
			+ "{|width=\"100%\"  border=\"1\" cellpadding=\"2\" cellspacing=\"0\"\r\n"
			+ "|-\r\n"
			+ "!What it looks like\r\n"
			+ "!What you type\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "<div style=\"font-size:150%;border-bottom:1px solid #000000;\">Section headings</div>\r\n"
			+ "\r\n"
			+ "\'\'Headings\'\' organize your writing into sections.\r\n"
			+ "The Wiki software can automatically generate\r\n"
			+ "a [[Help:table of contents|table of contents]] from them.\r\n"
			+ "\r\n"
			+ "<div style=\"font-size:132%;font-weight:bold;\">Subsection</div>\r\n"
			+ "Using more equals signs creates a subsection.\r\n"
			+ "\r\n"
			+ "<div style=\"font-size:116%;font-weight:bold;\">A smaller subsection</div>\r\n"
			+ "\r\n"
			+ "Don\'t skip levels, like from two to four equals signs.\r\n"
			+ "\r\n"
			+ "Start with 2 equals signs not 1 because 1 creates H1 tags which should be reserved for page title.\r\n"
			+ "|<pre>\r\n"
			+ "== Section headings ==\r\n"
			+ "\r\n"
			+ "\'\'Headings\'\' organize your writing into sections.\r\n"
			+ "The Wiki software can automatically generate\r\n"
			+ "a table of contents from them.\r\n"
			+ "\r\n"
			+ "=== Subsection ===\r\n"
			+ "\r\n"
			+ "Using more equals signs creates a subsection.\r\n"
			+ "\r\n"
			+ "==== A smaller subsection ====\r\n"
			+ "\r\n"
			+ "Don\'t skip levels, \r\n"
			+ "like from two to four equals signs.\r\n"
			+ "\r\n"
			+ "Start with 2 equals signs not 1 \r\n"
			+ "because 1 creates H1 tags\r\n"
			+ "which should be reserved for page title.\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "* \'\'Unordered [[Help:List|list]]s\'\' are easy to do:\r\n"
			+ "** Start every line with a star.\r\n"
			+ "*** More stars indicate a deeper level.\r\n"
			+ "*: Previous item continues.\r\n"
			+ "** A newline\r\n"
			+ "* in a list  \r\n"
			+ "marks the end of the list.\r\n"
			+ "*Of course you can start again.\r\n"
			+ "|<pre>\r\n"
			+ "* \'\'Unordered lists\'\' are easy to do:\r\n"
			+ "** Start every line with a star.\r\n"
			+ "*** More stars indicate a deeper level.\r\n"
			+ "*: Previous item continues.\r\n"
			+ "** A newline\r\n"
			+ "* in a list  \r\n"
			+ "marks the end of the list.\r\n"
			+ "* Of course you can start again.\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "# \'\'Numbered lists\'\' are:\r\n"
			+ "## Very organized\r\n"
			+ "## Easy to follow\r\n"
			+ "A newline marks the end of the list.\r\n"
			+ "# New numbering starts with 1.\r\n"
			+ "\r\n"
			+ "|<pre>\r\n"
			+ "# \'\'Numbered lists\'\' are also good:\r\n"
			+ "## Very organized\r\n"
			+ "## Easy to follow\r\n"
			+ "A newline marks the end of the list.\r\n"
			+ "# New numbering starts with 1.\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "Another kind of list is a \'\'definition list\'\':\r\n"
			+ "; Word : Definition of the word\r\n"
			+ "; Here is a longer phrase that needs a definition\r\n"
			+ ": Phrase defined\r\n"
			+ "; A word : Which has a definition\r\n"
			+ ": Also a second one\r\n"
			+ ": And even a third\r\n"
			+ "|<pre>\r\n"
			+ "Another kind of list is a \'\'definition list\'\':\r\n"
			+ "; Word : Definition of the word\r\n"
			+ "; Here is a longer phrase that needs a definition\r\n"
			+ ": Phrase defined\r\n"
			+ "; A word : Which has a definition\r\n"
			+ ": Also a second one\r\n"
			+ ": And even a third\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "* You can even do mixed lists\r\n"
			+ "*# and nest them\r\n"
			+ "*# inside each other\r\n"
			+ "*#* or break lines<br>in lists.\r\n"
			+ "*#; definition lists\r\n"
			+ "*#: can be \r\n"
			+ "*#;; nested too\r\n"
			+ "|<pre>\r\n"
			+ "* You can even do mixed lists\r\n"
			+ "*# and nest them\r\n"
			+ "*# inside each other\r\n"
			+ "*#* or break lines<br>in lists.\r\n"
			+ "*#; definition lists\r\n"
			+ "*#: can be \r\n"
			+ "*#;; nested too\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ ": A colon (:) indents a line or paragraph.\r\n"
			+ "A newline after that starts a new paragraph. <br>\r\n"
			+ "This is often used for discussion on [[talk pages]].\r\n"
			+ ": We use 1 colon to indent once.\r\n"
			+ ":: We use 2 colons to indent twice.\r\n"
			+ "::: We use 3 colons to indent 3 times, and so on.\r\n"
			+ "|<pre>\r\n"
			+ ": A colon (:) indents a line or paragraph.\r\n"
			+ "A newline after that starts a new paragraph. <br>\r\n"
			+ "This is often used for discussion on talk pages.\r\n"
			+ ": We use 1 colon to indent once.\r\n"
			+ ":: We use 2 colons to indent twice.\r\n"
			+ "::: We use 3 colons to indent 3 times, and so on.\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "You can make [[w:horizontal dividing line|horizontal dividing line]]s (----)\r\n"
			+ "to separate text.\r\n"
			+ "----\r\n"
			+ "But you should usually use sections instead,\r\n"
			+ "so that they go in the table of contents.\r\n"
			+ "|<pre>\r\n"
			+ "You can make horizontal dividing lines (----)\r\n"
			+ "to separate text.\r\n"
			+ "----\r\n"
			+ "But you should usually use sections instead,\r\n"
			+ "so that they go in the table of contents.\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "You can add footnotes to sentences using the \'\'ref\'\' tag -- this\r\n"
			+ "is especially good for citing a source.\r\n"
			+ "\r\n"
			+ ":There are over six billion people in the world.<ref>CIA World Factbook</ref>\r\n"
			+ "\r\n"
			+ "References: <references/>\r\n"
			+ "\r\n"
			+ "For details, see [[Wikipedia:Footnotes]] and [[Help:Footnotes]].\r\n"
			+ "|\r\n"
			+ "<pre><nowiki>\r\n"
			+ "You can add footnotes to sentences using the \'\'ref\'\' tag -- this\r\n"
			+ "is especially good for citing a source.\r\n"
			+ "\r\n"
			+ ":There are over six billion people in the world.<ref>CIA World Factbook</ref>\r\n"
			+ "\r\n"
			+ "References: <references/>\r\n"
			+ "\r\n"
			+ "For details, see [[Wikipedia:Footnotes]] and [[Help:Footnotes]].\r\n"
			+ "</nowiki></pre>\r\n"
			+ "|}\r\n"
			+ "\r\n"
			+ "=== Links ===\r\n"
			+ "\r\n"
			+ "You will often want to make clickable \'\'links\'\' to other pages.\r\n"
			+ "\r\n"
			+ "{|width=\"100%\"  border=\"1\" cellpadding=\"2\" cellspacing=\"0\"\r\n"
			+ "|-\r\n"
			+ "!What it looks like\r\n"
			+ "!What you type\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "Here\'s a link to a page named [[Official position]].\r\n"
			+ "You can even say [[official position]]s\r\n"
			+ "and the link will show up correctly.\r\n"
			+ "|<pre>\r\n"
			+ "Here\'s a link to a page named [[Official position]].\r\n"
			+ "You can even say [[official position]]s\r\n"
			+ "and the link will show up correctly.\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "You can put formatting around a link.\r\n"
			+ "Example: \'\'[[Wikipedia]]\'\'.\r\n"
			+ "|<pre>\r\n"
			+ "You can put formatting around a link.\r\n"
			+ "Example: \'\'[[Wikipedia]]\'\'.\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "The \'\'first letter\'\' of articles is automatically\r\n"
			+ "capitalized, so [[wikipedia]] goes to the same place\r\n"
			+ "as [[Wikipedia]]. Capitalization matters after the\r\n"
			+ "first letter.\r\n"
			+ "|<pre>\r\n"
			+ "The \'\'first letter\'\' of articles is automatically\r\n"
			+ "capitalized, so [[wikipedia]] goes to the same place\r\n"
			+ "as [[Wikipedia]]. Capitalization matters after the\r\n"
			+ "first letter.\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "[[The weather in Moscow]] is a page that doesn\'t exist\r\n"
			+ "yet. You could create it by clicking on the link.\r\n"
			+ "|<pre>\r\n"
			+ "[[The weather in Moscow]] is a page that doesn\'t exist\r\n"
			+ "yet. You could create it by clicking on the link.\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "You can link to a page section by its title:\r\n"
			+ "\r\n"
			+ "*[[List of cities by country#Morocco]].\r\n"
			+ "\r\n"
			+ "If multiple sections have the same title, add\r\n"
			+ "a number. [[#Example section 3]] goes to the\r\n"
			+ "third section named \"Example section\".\r\n"
			+ "|<pre>\r\n"
			+ "You can link to a page section by its title:\r\n"
			+ "\r\n"
			+ "*[[List of cities by country#Morocco]].\r\n"
			+ "\r\n"
			+ "If multiple sections have the same title, add\r\n"
			+ "a number. [[#Example section 3]] goes to the\r\n"
			+ "third section named \"Example section\".\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "You can make a link point to a different place\r\n"
			+ "with a [[Help:Piped link|piped link]]. Put the link\r\n"
			+ "target first, then the pipe character \"|\", then\r\n"
			+ "the link text.\r\n"
			+ "\r\n"
			+ "*[[Help:Link|About Links]]\r\n"
			+ "*[[List of cities by country#Morocco|\r\n"
			+ "Cities in Morocco]]\r\n"
			+ "|<pre>\r\n"
			+ "You can make a link point to a different place\r\n"
			+ "with a [[Help:Piped link|piped link]]. Put the link\r\n"
			+ "target first, then the pipe character \"|\", then\r\n"
			+ "the link text.\r\n"
			+ "\r\n"
			+ "*[[Help:Link|About Links]]\r\n"
			+ "*[[List of cities by country#Morocco|\r\n"
			+ "Cities in Morocco]]\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "You can make an external link just by typing a URL:\r\n"
			+ "http://www.nupedia.com\r\n"
			+ "\r\n"
			+ "You can give it a title:\r\n"
			+ "[http://www.nupedia.com Nupedia]\r\n"
			+ "\r\n"
			+ "Or leave the title blank:\r\n"
			+ "[http://www.nupedia.com]\r\n"
			+ "|\r\n"
			+ "<pre>\r\n"
			+ "You can make an external link just by typing a URL:\r\n"
			+ "http://www.nupedia.com\r\n"
			+ "\r\n"
			+ "You can give it a title:\r\n"
			+ "[http://www.nupedia.com Nupedia]\r\n"
			+ "\r\n"
			+ "Or leave the title blank:\r\n"
			+ "[http://www.nupedia.com]\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "Linking to an e-mail address works the same way:\r\n"
			+ "mailto:someone@domain.com or \r\n"
			+ "[mailto:someone@domain.com someone]\r\n"
			+ "|\r\n"
			+ "<pre>\r\n"
			+ "Linking to an e-mail address works the same way:\r\n"
			+ "mailto:someone@domain.com or \r\n"
			+ "[mailto:someone@domain.com someone]\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "You can [[Help:Redirect|redirect]] the user to another page.\r\n"
			+ "|<pre>\r\n"
			+ "#REDIRECT [[Official position]]\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "The Wiki reformats linked dates to match the reader\'s\r\n"
			+ "date preferences. These three dates will show up the\r\n"
			+ "same if you choose a format in your\r\n"
			+ "[[Special:Preferences|Preferences]]:\r\n"
			+ "* [[July 20]], [[1969]]\r\n"
			+ "* [[20 July]] [[1969]]\r\n"
			+ "* [[1969]]-[[07-20]]\r\n"
			+ "|<pre>\r\n"
			+ "The Wiki reformats linked dates to match the reader\'s\r\n"
			+ "date preferences. These three dates will show up the\r\n"
			+ "same if you choose a format in your\r\n"
			+ "[[Special:Preferences|]]:\r\n"
			+ "* [[July 20]], [[1969]]\r\n"
			+ "* [[20 July]] [[1969]]\r\n"
			+ "* [[1969]]-[[07-20]]\r\n"
			+ "</pre>\r\n"
			+ "|}\r\n"
			+ "\r\n"
			+ "===Just show what I typed===\r\n"
			+ "\r\n"
			+ "A few different kinds of formatting will tell the Wiki to display things as you typed them.\r\n"
			+ "\r\n"
			+ "{| border=\"1\" cellpadding=\"2\" cellspacing=\"0\"\r\n"
			+ "|-\r\n"
			+ "!What it looks like\r\n"
			+ "!What you type\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "<nowiki>\r\n"
			+ "The nowiki tag ignores [[Wiki]] \'\'markup\'\'.\r\n"
			+ "It reformats text by removing\r\n"
			+ "newlines    and multiple spaces.\r\n"
			+ "It still interprets special\r\n"
			+ "characters: &rarr;\r\n"
			+ "</nowiki>\r\n"
			+ "|<pre>\r\n"
			+ "&lt;nowiki&gt;\r\n"
			+ "The nowiki tag ignores [[Wiki]] \'\'markup\'\'.\r\n"
			+ "It reformats text by removing\r\n"
			+ "newlines    and multiple spaces.\r\n"
			+ "It still interprets special\r\n"
			+ "characters: &amp;rarr;\r\n"
			+ "&lt;/nowiki&gt;\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "<pre>\r\n"
			+ "The pre tag ignores [[Wiki]] \'\'markup\'\'.\r\n"
			+ "It also doesn\'t     reformat text.\r\n"
			+ "It still interprets special characters: &rarr;\r\n"
			+ "</pre>\r\n"
			+ "|<pre>\r\n"
			+ "&lt;pre&gt;\r\n"
			+ "The pre tag ignores [[Wiki]] \'\'markup\'\'.\r\n"
			+ "It also doesn\'t     reformat text.\r\n"
			+ "It still interprets special characters: &amp;rarr;\r\n"
			+ "&lt;/pre&gt;\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "Leading spaces are another way to preserve formatting.\r\n"
			+ "\r\n"
			+ " Putting a space at the beginning of each\r\n"
			+ " line stops the text   from being reformatted.\r\n"
			+ " It still interprets [[Wiki]] \'\'markup\'\' and\r\n"
			+ " special characters: &rarr;\r\n"
			+ "|<pre>\r\n"
			+ "Leading spaces are another way to preserve formatting.\r\n"
			+ "\r\n"
			+ " Putting a space at the beginning of each\r\n"
			+ " line stops the text   from being reformatted.\r\n"
			+ " It still interprets [[Wiki]] \'\'markup\'\' and\r\n"
			+ " special characters: &amp;rarr;\r\n"
			+ "</pre>\r\n"
			+ "|}\r\n"
			+ "\r\n"
			+ "===Images, tables, video, and sounds===\r\n"
			+ "\r\n"
			+ "After uploading, just enter the filename, highlight it and press the \"embedded image\"-button of the edit_toolbar.\r\n"
			+ "\r\n"
			+ "This will produce the sytax for uploading a file \'\'\'<nowiki>[[Image:filename.png]]</nowiki>\'\'\'\r\n"
			+ "\r\n"
			+ "{| border=\"1\" cellpadding=\"2\" cellspacing=\"0\"\r\n"
			+ "|-\r\n"
			+ "!What it looks like\r\n"
			+ "!What you type\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "A picture, including alternate text:\r\n"
			+ "\r\n"
			+ "[[Image:collaboration w text.gif|The logo for this Wiki]]\r\n"
			+ "\r\n"
			+ "You can put the image in a frame with a caption:\r\n"
			+ "[[Image:collaboration w text.gif|frame|The logo for this Wiki]]\r\n"
			+ "|<pre>\r\n"
			+ "A picture, including alternate text:\r\n"
			+ "\r\n"
			+ "[[Image:collaboration w text.gif|The logo for this Wiki]]\r\n"
			+ "\r\n"
			+ "You can put the image in a frame with a caption:\r\n"
			+ "[[Image:collaboration w text.gif|frame|The logo for this Wiki]]\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "A link to the page for the image:\r\n"
			+ "[[:Image:collaboration w text.gif]]\r\n"
			+ "|<pre>\r\n"
			+ "A link to the page for the image:\r\n"
			+ "[[:Image:collaboration w text.gif]]\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "Use \'\'\'media:\'\'\' links to link directly to sounds\r\n"
			+ "or videos: [[media:Sg_mrob.ogg|A sound file]]\r\n"
			+ "|<pre>\r\n"
			+ "Use \'\'\'media:\'\'\' links to link directly to sounds\r\n"
			+ "or videos: [[media:Sg_mrob.ogg|A sound file]]\r\n"
			+ "</pre>\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "{| border=\"1\" cellspacing=\"0\" cellpadding=\"5\" align=\"center\"\r\n"
			+ "! This\r\n"
			+ "! is\r\n"
			+ "|- \r\n"
			+ "| a\r\n"
			+ "| table\r\n"
			+ "|-\r\n"
			+ "|}\r\n"
			+ "|<pre>\r\n"
			+ "{| border=\"1\" cellspacing=\"0\" cellpadding=\"5\" align=\"center\"\r\n"
			+ "! This\r\n"
			+ "! is\r\n"
			+ "|- \r\n"
			+ "| a\r\n"
			+ "| table\r\n"
			+ "|-\r\n"
			+ "|}\r\n"
			+ "\r\n"
			+ "</pre>\r\n"
			+ "|}\r\n"
			+ "\r\n"
			+ "===Templates===\r\n"
			+ "\r\n"
			+ "\'\'\'Templates\'\'\' are segments of Wiki markup that are meant to be copied automatically (\"transcluded\") into a page.\r\n"
			+ "You add them by putting the template\'s name in <nowiki>{{double braces}}</nowiki>.\r\n"
			+ "\r\n"
			+ "Some templates take \'\'parameters\'\', as well, which you separate with the pipe character.\r\n"
			+ "{| border=\"1\" cellpadding=\"2\" cellspacing=\"0\" width=\"100%\"\r\n"
			+ "|-\r\n"
			+ "!What it looks like\r\n"
			+ "!What you type\r\n"
			+ "|-\r\n"
			+ "|\r\n"
			+ "{{alert|content=test content}}\r\n"
			+ "|<pre>\r\n"
			+ "{{alert|content=test content}}\r\n"
			+ "</pre>\r\n"
			+ "|}\r\n"
			+ "== Minor edits ==\r\n"
			+ "\r\n"
			+ "A logged-in user can mark an edit as \"minor\". Minor edits are generally spelling corrections, formatting, and minor rearrangement of text. Users may choose to \'\'hide\'\' minor edits when viewing Recent Changes.\r\n"
			+ "\r\n"
			+ "Marking a significant change as a minor edit is considered bad Wikiquette. If you have accidentally marked an edit as minor, make a dummy edit, verify that the \"<small>\'\'\'[&nbsp;] This is a minor edit\'\'\'</small>\" check-box is unchecked, and explain in the edit summary that the previous edit was not minor.\r\n"
			+ "\r\n"
			+ "==See also==\r\n"
			+ "\r\n"
			+ "*[[Help:Starting a new page]]\r\n"
			+ "\r\n"
			+ "[[Category:MediaWiki Documentation]]\r\n" + "";

	public BigRenderTest(String name) {
		super(name);
	}

	public static Test suite() {
		return new TestSuite(BigRenderTest.class);
	}

	public void test999() {
		for (int i = 0; i < 100; i++) {
			wikiModel.render(TEST1);
		}
	}

}
