package info.bliki.html.test;

import info.bliki.html.HTML2WikiConverter;
import info.bliki.html.wikipedia.ToWikipedia;
import junit.framework.TestCase;

public class BigHTML2WikipediaTest extends TestCase {
	private static final String BIG_HTML = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
			+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"de\" lang=\"de\" dir=\"ltr\">\r\n"
			+ "	<head>\r\n"
			+ "		<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n"
			+ "				<meta name=\"keywords\" content=\"Afrikanischer Strauß,Hauptseite,,Afrika,Akne,Altgriechische Sprache,Arabische Halbinsel,Art (Biologie),Arthritis,Auge,Australien\" />\r\n"
			+ "		<link rel=\"shortcut icon\" href=\"/favicon.ico\" />\r\n"
			+ "		<link rel=\"search\" type=\"application/opensearchdescription+xml\" href=\"/w/opensearch_desc.php\" title=\"Wikipedia (Deutsch)\" />\r\n"
			+ "		<link rel=\"copyright\" href=\"http://www.gnu.org/copyleft/fdl.html\" />\r\n"
			+ "		<title>Afrikanischer Strauß - Wikipedia</title>\r\n"
			+ "\r\n"
			+ "		<style type=\"text/css\" media=\"screen,projection\">/*<![CDATA[*/ @import \"/skins-1.5/monobook/main.css?56\"; /*]]>*/</style>\r\n"
			+ "		<link rel=\"stylesheet\" type=\"text/css\" media=\"print\" href=\"/skins-1.5/common/commonPrint.css?56\" />\r\n"
			+ "		<link rel=\"stylesheet\" type=\"text/css\" media=\"handheld\" href=\"/skins-1.5/monobook/handheld.css?56\" />\r\n"
			+ "		<!--[if lt IE 5.5000]><style type=\"text/css\">@import \"/skins-1.5/monobook/IE50Fixes.css?56\";</style><![endif]-->\r\n"
			+ "		<!--[if IE 5.5000]><style type=\"text/css\">@import \"/skins-1.5/monobook/IE55Fixes.css?56\";</style><![endif]-->\r\n"
			+ "		<!--[if IE 6]><style type=\"text/css\">@import \"/skins-1.5/monobook/IE60Fixes.css?56\";</style><![endif]-->\r\n"
			+ "		<!--[if IE 7]><style type=\"text/css\">@import \"/skins-1.5/monobook/IE70Fixes.css?56\";</style><![endif]-->\r\n"
			+ "		<!--[if lt IE 7]><script type=\"text/javascript\" src=\"/skins-1.5/common/IEFixes.js?56\"></script>\r\n"
			+ "		<meta http-equiv=\"imagetoolbar\" content=\"no\" /><![endif]-->\r\n"
			+ "\r\n"
			+ "		\r\n"
			+ "		<script type= \"text/javascript\">/*<![CDATA[*/\r\n"
			+ "var skin = \"monobook\";\r\n"
			+ "var stylepath = \"/skins-1.5\";\r\n"
			+ "var wgArticlePath = \"/wiki/$1\";\r\n"
			+ "var wgScriptPath = \"/w\";\r\n"
			+ "var wgServer = \"http://de.wikipedia.org\";\r\n"
			+ "var wgCanonicalNamespace = \"\";\r\n"
			+ "var wgCanonicalSpecialPageName = false;\r\n"
			+ "var wgNamespaceNumber = 0;\r\n"
			+ "var wgPageName = \"Afrikanischer_Strauß\";\r\n"
			+ "var wgTitle = \"Afrikanischer Strauß\";\r\n"
			+ "var wgArticleId = \"4786\";\r\n"
			+ "var wgIsArticle = true;\r\n"
			+ "var wgUserName = null;\r\n"
			+ "var wgUserGroups = null;\r\n"
			+ "var wgUserLanguage = \"de\";\r\n"
			+ "var wgContentLanguage = \"de\";\r\n"
			+ "var wgBreakFrames = false;\r\n"
			+ "var wgCurRevisionId = \"27853050\";\r\n"
			+ "/*]]>*/</script>\r\n"
			+ "                \r\n"
			+ "		<script type=\"text/javascript\" src=\"/skins-1.5/common/wikibits.js?56\"><!-- wikibits js --></script>\r\n"
			+ "		<script type=\"text/javascript\" src=\"/w/index.php?title=-&amp;action=raw&amp;gen=js\"><!-- site js --></script>\r\n"
			+ "		<style type=\"text/css\">/*<![CDATA[*/\r\n"
			+ "@import \"/w/index.php?title=MediaWiki:Common.css&usemsgcache=yes&action=raw&ctype=text/css&smaxage=2678400\";\r\n"
			+ "@import \"/w/index.php?title=MediaWiki:Monobook.css&usemsgcache=yes&action=raw&ctype=text/css&smaxage=2678400\";\r\n"
			+ "@import \"/w/index.php?title=-&action=raw&gen=css&maxage=2678400\";\r\n"
			+ "/*]]>*/</style>\r\n"
			+ "		<!-- Head Scripts -->\r\n"
			+ "		<script type=\"text/javascript\" src=\"/skins-1.5/common/ajax.js?56\"></script>\r\n"
			+ "\r\n"
			+ "	</head>\r\n"
			+ "<body  class=\"mediawiki ns-0 ltr page-Afrikanischer_Strauß\">\r\n"
			+ "	<div id=\"globalWrapper\">\r\n"
			+ "		<div id=\"column-content\">\r\n"
			+ "	<div id=\"content\">\r\n"
			+ "		<a name=\"top\" id=\"top\"></a>\r\n"
			+ "				<h1 class=\"firstHeading\">Afrikanischer Strauß</h1>\r\n"
			+ "		<div id=\"bodyContent\">\r\n"
			+ "			<h3 id=\"siteSub\">aus Wikipedia, der freien Enzyklopädie</h3>\r\n"
			+ "\r\n"
			+ "			<div id=\"contentSub\"></div>\r\n"
			+ "									<div id=\"jump-to-nav\">Wechseln zu: <a href=\"#column-one\">Navigation</a>, <a href=\"#searchInput\">Suche</a></div>			<!-- start content -->\r\n"
			+ "			<table class=\"taxobox\">\r\n"
			+ "<tr>\r\n"
			+ "<th>Afrikanischer Strauß</th>\r\n"
			+ "</tr>\r\n"
			+ "<tr>\r\n"
			+ "<td class=\"taxo-bild\">\r\n"
			+ "\r\n"
			+ "<div class=\"thumb tright\">\r\n"
			+ "<div class=\"thumbinner\" style=\"width:302px;\"><a href=\"/wiki/Bild:StrausseNgorongoroKrater1977.jpg\" class=\"internal\" title=\"Straußenpaar im Ngorongoro-Krater\"><img src=\"http://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/StrausseNgorongoroKrater1977.jpg/300px-StrausseNgorongoroKrater1977.jpg\" alt=\"Straußenpaar im Ngorongoro-Krater\" width=\"300\" height=\"200\" longdesc=\"/wiki/Bild:StrausseNgorongoroKrater1977.jpg\" class=\"thumbimage\" /></a>\r\n"
			+ "<div class=\"thumbcaption\">\r\n"
			+ "<div class=\"magnify\" style=\"float:right\"><a href=\"/wiki/Bild:StrausseNgorongoroKrater1977.jpg\" class=\"internal\" title=\"vergrößern\"><img src=\"/skins-1.5/common/images/magnify-clip.png\" width=\"15\" height=\"11\" alt=\"\" /></a></div>\r\n"
			+ "Straußenpaar im <a href=\"/wiki/Ngorongoro-Krater\" title=\"Ngorongoro-Krater\">Ngorongoro-Krater</a></div>\r\n"
			+ "</div>\r\n"
			+ "</div>\r\n"
			+ "</td>\r\n"
			+ "</tr>\r\n"
			+ "<tr>\r\n"
			+ "<th><b><a href=\"/wiki/Systematik_%28Biologie%29\" title=\"Systematik (Biologie)\">Systematik</a></b></th>\r\n"
			+ "</tr>\r\n"
			+ "<tr>\r\n"
			+ "<td>\r\n"
			+ "\r\n"
			+ "<table>\r\n"
			+ "<tr>\r\n"
			+ "<td><i><a href=\"/wiki/Klasse_%28Biologie%29\" title=\"Klasse (Biologie)\">Klasse</a>:</i></td>\r\n"
			+ "<td><a href=\"/wiki/V%C3%B6gel\" title=\"Vögel\">Vögel</a> (Aves)</td>\r\n"
			+ "</tr>\r\n"
			+ "<tr>\r\n"
			+ "<td><i><a href=\"/wiki/Klasse_%28Biologie%29\" title=\"Klasse (Biologie)\">Unterklasse</a>:</i></td>\r\n"
			+ "<td><a href=\"/wiki/Urkieferv%C3%B6gel\" title=\"Urkiefervögel\">Urkiefervögel</a> (Palaeognathae)</td>\r\n"
			+ "\r\n"
			+ "</tr>\r\n"
			+ "<tr>\r\n"
			+ "<td><i><a href=\"/wiki/Ordnung_%28Biologie%29\" title=\"Ordnung (Biologie)\">Ordnung</a>:</i></td>\r\n"
			+ "<td><a href=\"/wiki/Laufv%C3%B6gel\" title=\"Laufvögel\">Laufvögel</a> (Struthioniformes)</td>\r\n"
			+ "</tr>\r\n"
			+ "<tr>\r\n"
			+ "<td><i><a href=\"/wiki/Familie_%28Biologie%29\" title=\"Familie (Biologie)\">Familie</a>:</i></td>\r\n"
			+ "<td>Strauße (Struthionidae)</td>\r\n"
			+ "</tr>\r\n"
			+ "\r\n"
			+ "<tr>\r\n"
			+ "<td><i><a href=\"/wiki/Gattung_%28Biologie%29\" title=\"Gattung (Biologie)\">Gattung</a>:</i></td>\r\n"
			+ "<td>Strauße (<i>Struthio</i>)</td>\r\n"
			+ "</tr>\r\n"
			+ "<tr>\r\n"
			+ "<td><i><a href=\"/wiki/Art_%28Biologie%29\" title=\"Art (Biologie)\">Art</a>:</i></td>\r\n"
			+ "<td>Afrikanischer Strauß</td>\r\n"
			+ "</tr>\r\n"
			+ "</table>\r\n"
			+ "\r\n"
			+ "</td>\r\n"
			+ "</tr>\r\n"
			+ "<tr>\r\n"
			+ "<th><a href=\"/wiki/Nomenklatur_%28Biologie%29\" title=\"Nomenklatur (Biologie)\">Wissenschaftlicher Name</a></th>\r\n"
			+ "</tr>\r\n"
			+ "<tr>\r\n"
			+ "<td class=\"taxo-name\"><i>Struthio camelus</i></td>\r\n"
			+ "</tr>\r\n"
			+ "<tr>\r\n"
			+ "<td class=\"Person\"><a href=\"/wiki/Carl_von_Linn%C3%A9\" title=\"Carl von Linné\">Linnaeus</a>, 1758</td>\r\n"
			+ "</tr>\r\n"
			+ "</table>\r\n"
			+ "<p>Der <b>Afrikanische Strauß</b> (<i>Struthio camelus</i>) gehört zu den <a href=\"/wiki/Laufv%C3%B6gel\" title=\"Laufvögel\">Laufvögeln</a> und ist der größte lebende <a href=\"/wiki/V%C3%B6gel\" title=\"Vögel\">Vogel</a> der Erde. Während er heute nur noch in Afrika südlich der Sahara heimisch ist, war er in früheren Zeiten auch in Westasien beheimatet. Für den Menschen war der Strauß wegen seiner Federn, seines Fleisches und seines Leders seit jeher von Interesse, was in vielen Regionen zur Ausrottung des Vogels führte.</p>\r\n"
			+ "\r\n"
			+ "<table id=\"toc\" class=\"toc\" summary=\"Inhaltsverzeichnis\">\r\n"
			+ "<tr>\r\n"
			+ "<td>\r\n"
			+ "<div id=\"toctitle\">\r\n"
			+ "<h2>Inhaltsverzeichnis</h2>\r\n"
			+ "</div>\r\n"
			+ "<ul>\r\n"
			+ "<li class=\"toclevel-1\"><a href=\"#Merkmale\"><span class=\"tocnumber\">1</span> <span class=\"toctext\">Merkmale</span></a></li>\r\n"
			+ "<li class=\"toclevel-1\"><a href=\"#Stimme\"><span class=\"tocnumber\">2</span> <span class=\"toctext\">Stimme</span></a></li>\r\n"
			+ "<li class=\"toclevel-1\"><a href=\"#Verbreitung_und_Lebensraum\"><span class=\"tocnumber\">3</span> <span class=\"toctext\">Verbreitung und Lebensraum</span></a></li>\r\n"
			+ "\r\n"
			+ "<li class=\"toclevel-1\"><a href=\"#Lebensweise\"><span class=\"tocnumber\">4</span> <span class=\"toctext\">Lebensweise</span></a>\r\n"
			+ "<ul>\r\n"
			+ "<li class=\"toclevel-2\"><a href=\"#Aktivit.C3.A4t\"><span class=\"tocnumber\">4.1</span> <span class=\"toctext\">Aktivität</span></a></li>\r\n"
			+ "<li class=\"toclevel-2\"><a href=\"#Sozialverhalten\"><span class=\"tocnumber\">4.2</span> <span class=\"toctext\">Sozialverhalten</span></a></li>\r\n"
			+ "<li class=\"toclevel-2\"><a href=\"#Ern.C3.A4hrung\"><span class=\"tocnumber\">4.3</span> <span class=\"toctext\">Ernährung</span></a></li>\r\n"
			+ "\r\n"
			+ "<li class=\"toclevel-2\"><a href=\"#Feinde\"><span class=\"tocnumber\">4.4</span> <span class=\"toctext\">Feinde</span></a></li>\r\n"
			+ "<li class=\"toclevel-2\"><a href=\"#Fortpflanzung\"><span class=\"tocnumber\">4.5</span> <span class=\"toctext\">Fortpflanzung</span></a></li>\r\n"
			+ "</ul>\r\n"
			+ "</li>\r\n"
			+ "<li class=\"toclevel-1\"><a href=\"#Stammesgeschichte_und_Systematik\"><span class=\"tocnumber\">5</span> <span class=\"toctext\">Stammesgeschichte und Systematik</span></a>\r\n"
			+ "<ul>\r\n"
			+ "<li class=\"toclevel-2\"><a href=\"#Fossilgeschichte\"><span class=\"tocnumber\">5.1</span> <span class=\"toctext\">Fossilgeschichte</span></a></li>\r\n"
			+ "\r\n"
			+ "</ul>\r\n"
			+ "</li>\r\n"
			+ "<li class=\"toclevel-1\"><a href=\"#Strau.C3.9F_und_Mensch\"><span class=\"tocnumber\">6</span> <span class=\"toctext\">Strauß und Mensch</span></a></li>\r\n"
			+ "<li class=\"toclevel-1\"><a href=\"#Etymologie\"><span class=\"tocnumber\">7</span> <span class=\"toctext\">Etymologie</span></a></li>\r\n"
			+ "<li class=\"toclevel-1\"><a href=\"#Literatur\"><span class=\"tocnumber\">8</span> <span class=\"toctext\">Literatur</span></a></li>\r\n"
			+ "<li class=\"toclevel-1\"><a href=\"#Weblinks\"><span class=\"tocnumber\">9</span> <span class=\"toctext\">Weblinks</span></a></li>\r\n"
			+ "\r\n"
			+ "</ul>\r\n"
			+ "</td>\r\n"
			+ "</tr>\r\n"
			+ "</table>\r\n"
			+ "<p><script type=\"text/javascript\">\r\n"
			+ "//<![CDATA[\r\n"
			+ " if (window.showTocToggle) { var tocShowText = \"Anzeigen\"; var tocHideText = \"Verbergen\"; showTocToggle(); } \r\n"
			+ "//]]>\r\n"
			+ "</script><a name=\"Merkmale\" id=\"Merkmale\"></a></p>\r\n"
			+ "<h2><span class=\"mw-headline\">Merkmale</span></h2>\r\n"
			+ "<p>Die Männchen des Straußes sind 210 bis 275 Zentimeter hoch und haben ein Gewicht von 100 bis 130, seltener bis 150 Kilogramm. Weibchen sind kleiner: Sie sind 175 bis 190 Zentimeter hoch und 90 bis 110 Kilogramm schwer.</p>\r\n"
			+ "<p>Die Männchen, Hähne genannt, haben ein schwarzes Gefieder. Davon setzen sich die Schwungfedern der Flügel und der Schwanz weiß ab. Die Weibchen, Hennen genannt, haben dagegen ein eher unscheinbares, erdbraunes <a href=\"/wiki/Gefieder\" title=\"Gefieder\">Gefieder</a>; Flügel und Schwanz sind auch bei ihnen heller und haben eine weißlichgraue Farbe. Das Jugendkleid ähnelt dem Aussehen des Weibchens, aber ohne die charakteristische Absetzung von Flügeln und Schwanz. Die nackten Beine sowie der Hals sind je nach Unterart grau, graublau oder rosafarben. Beim Männchen leuchtet die Haut während der Brutzeit besonders intensiv.</p>\r\n"
			+ "<div class=\"thumb tleft\">\r\n"
			+ "<div class=\"thumbinner\" style=\"width:202px;\"><a href=\"/wiki/Bild:Strau%C3%9F1.jpg\" class=\"internal\" title=\"Nahaufnahme eines Straußenkopfes\"><img src=\"http://upload.wikimedia.org/wikipedia/de/thumb/2/29/Strau%C3%9F1.jpg/200px-Strau%C3%9F1.jpg\" alt=\"Nahaufnahme eines Straußenkopfes\" width=\"200\" height=\"150\" longdesc=\"/wiki/Bild:Strau%C3%9F1.jpg\" class=\"thumbimage\" /></a>\r\n"
			+ "<div class=\"thumbcaption\">\r\n"
			+ "\r\n"
			+ "<div class=\"magnify\" style=\"float:right\"><a href=\"/wiki/Bild:Strau%C3%9F1.jpg\" class=\"internal\" title=\"vergrößern\"><img src=\"/skins-1.5/common/images/magnify-clip.png\" width=\"15\" height=\"11\" alt=\"\" /></a></div>\r\n"
			+ "Nahaufnahme eines Straußenkopfes</div>\r\n"
			+ "</div>\r\n"
			+ "</div>\r\n"
			+ "<p>Der Strauß hat ferner einen langen Hals, der überwiegend nackt ist. Der Kopf ist in Relation zum Körper klein. Die <a href=\"/wiki/Auge\" title=\"Auge\">Augen</a> sind allerdings mit einem Durchmesser von 5 Zentimetern die größten aller Landwirbeltiere.</p>\r\n"
			+ "<div class=\"thumb tright\">\r\n"
			+ "<div class=\"thumbinner\" style=\"width:182px;\"><a href=\"/wiki/Bild:Pelvis_ostrich_ventralview.jpg\" class=\"internal\" title=\"Becken und Synsacrum eines Straußes von unten (ventral). 1 Schambein, 2 Sitzbein, 3 Darmbein, 4 Symphyse, 5 Synsacrum, 6 Nierengruben (Fossae renales), 7 Oberschenkelknochen, 8 Pygostyl\"><img src=\"http://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Pelvis_ostrich_ventralview.jpg/180px-Pelvis_ostrich_ventralview.jpg\" alt=\"Becken und Synsacrum eines Straußes von unten (ventral). 1 Schambein, 2 Sitzbein, 3 Darmbein, 4 Symphyse, 5 Synsacrum, 6 Nierengruben (Fossae renales), 7 Oberschenkelknochen, 8 Pygostyl\" width=\"180\" height=\"104\" longdesc=\"/wiki/Bild:Pelvis_ostrich_ventralview.jpg\" class=\"thumbimage\" /></a>\r\n"
			+ "<div class=\"thumbcaption\">\r\n"
			+ "<div class=\"magnify\" style=\"float:right\"><a href=\"/wiki/Bild:Pelvis_ostrich_ventralview.jpg\" class=\"internal\" title=\"vergrößern\"><img src=\"/skins-1.5/common/images/magnify-clip.png\" width=\"15\" height=\"11\" alt=\"\" /></a></div>\r\n"
			+ "Becken und Synsacrum eines Straußes von unten (<a href=\"/wiki/Ventral\" title=\"Ventral\">ventral</a>). <small>1 Schambein, 2 Sitzbein, 3 Darmbein, 4 Symphyse, 5 Synsacrum, 6 Nierengruben (<i>Fossae renales</i>), 7 <a href=\"/wiki/Oberschenkelknochen\" title=\"Oberschenkelknochen\">Oberschenkelknochen</a>, 8 <a href=\"/wiki/Pygostyl\" title=\"Pygostyl\">Pygostyl</a></small></div>\r\n"
			+ "\r\n"
			+ "</div>\r\n"
			+ "</div>\r\n"
			+ "<p>Das <a href=\"/wiki/Becken_%28Anatomie%29\" title=\"Becken (Anatomie)\">Becken</a> der Strauße ist <a href=\"/wiki/Ventral\" title=\"Ventral\">ventral</a> durch eine <a href=\"/wiki/Schambeinfuge\" title=\"Schambeinfuge\">Schambeinfuge</a> (<i>Symphysis pubica</i>) geschlossen. Bei allen nicht-straußenartigen Vögeln ist dies nicht der Fall. Es wird von den drei spangenartigen Beckenknochen (<a href=\"/wiki/Darmbein\" title=\"Darmbein\">Darmbein</a>, <a href=\"/wiki/Sitzbein\" title=\"Sitzbein\">Sitzbein</a>, <a href=\"/wiki/Schambein\" title=\"Schambein\">Schambein</a>) gebildet, zwischen denen große Öffnungen bestehen, die durch <a href=\"/wiki/Bindegewebe\" title=\"Bindegewebe\">Bindegewebe</a> und <a href=\"/wiki/Muskulatur\" title=\"Muskulatur\">Muskulatur</a> verschlossen sind. Der Strauß hat sehr lange Beine mit einer kräftigen Laufmuskulatur. Seine Höchstgeschwindigkeit beträgt etwa 70 km/h; eine Geschwindigkeit von 50 km/h kann der Strauß etwa eine halbe Stunde halten. Als Anpassung an die hohe Laufgeschwindigkeit besitzt der <a href=\"/wiki/Vogelfu%C3%9F\" title=\"Vogelfuß\">Fuß</a>, einzigartig bei Vögeln, nur zwei <a href=\"/wiki/Zehe_%28Fu%C3%9F%29\" title=\"Zehe (Fuß)\">Zehen</a> (<i>Didactylie</i>). Zudem können die Beine als wirkungsvolle Waffen eingesetzt werden. Beide Zehen tragen <a href=\"/wiki/Kralle\" title=\"Kralle\">Krallen</a>, die an der größeren inneren Zehe bis zu 10 Zentimeter lang ist.</p>\r\n"
			+ "\r\n"
			+ "<div class=\"thumb tright\">\r\n"
			+ "<div class=\"thumbinner\" style=\"width:182px;\"><a href=\"/wiki/Bild:Shoulder_girdle-ostrich.jpg\" class=\"internal\" title=\"Skelett eines Straußes von vorn. 1 Brustbein, 2 Rabenbein, 3 Schlüsselbein, 4 Schulterblatt, 5 Oberarm, 6 Rippen, 7 Oberschenkel, 8 Schienbein, 9 Wadenbein\"><img src=\"http://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Shoulder_girdle-ostrich.jpg/180px-Shoulder_girdle-ostrich.jpg\" alt=\"Skelett eines Straußes von vorn. 1 Brustbein, 2 Rabenbein, 3 Schlüsselbein, 4 Schulterblatt, 5 Oberarm, 6 Rippen, 7 Oberschenkel, 8 Schienbein, 9 Wadenbein\" width=\"180\" height=\"135\" longdesc=\"/wiki/Bild:Shoulder_girdle-ostrich.jpg\" class=\"thumbimage\" /></a>\r\n"
			+ "<div class=\"thumbcaption\">\r\n"
			+ "<div class=\"magnify\" style=\"float:right\"><a href=\"/wiki/Bild:Shoulder_girdle-ostrich.jpg\" class=\"internal\" title=\"vergrößern\"><img src=\"/skins-1.5/common/images/magnify-clip.png\" width=\"15\" height=\"11\" alt=\"\" /></a></div>\r\n"
			+ "Skelett eines Straußes von vorn. <small>1 Brustbein, 2 Rabenbein, 3 Schlüsselbein, 4 Schulterblatt, 5 Oberarm, 6 Rippen, 7 Oberschenkel, 8 Schienbein, 9 Wadenbein</small></div>\r\n"
			+ "</div>\r\n"
			+ "</div>\r\n"
			+ "<p>Das <a href=\"/wiki/Sternum\" title=\"Sternum\">Brustbein</a> (<i>Sternum</i>) trägt, wie bei allen Straußenartigen, keinen Brustbeinkamm. Dadurch wirkt es platt und flach wie ein <a href=\"/wiki/Flo%C3%9F\" title=\"Floß\">Floß</a> (lat. <i>Ratis</i>), weshalb diese Vogelgruppe auch als <a href=\"/wiki/Ratiten\" title=\"Ratiten\">Ratiten</a> bezeichnet wird. Wie alle Vögel besitzt auch der Strauß einen vollständigen <a href=\"/wiki/Schulterg%C3%BCrtel\" title=\"Schultergürtel\">Schultergürtel</a>. Ein Besonderheit ist die starke Verschmelzung von <a href=\"/wiki/Coracoid\" title=\"Coracoid\">Rabenbein</a> (<i>Os coracoideum</i>) und <a href=\"/wiki/Clavicula\" title=\"Clavicula\">Schlüsselbein</a> (<i>Clavicula</i>), zwischen denen lediglich ein ovales Loch offen bleibt.</p>\r\n"
			+ "\r\n"
			+ "<p>Die <a href=\"/wiki/Vogelfl%C3%BCgel\" title=\"Vogelflügel\">Flügel</a> sind für Laufvögel recht groß, aber wie bei allen <a href=\"/wiki/Laufv%C3%B6gel\" title=\"Laufvögel\">Laufvögeln</a> nicht zum Fliegen geeignet. Das Eigengewicht eines Straußes liegt weit über dem Gewicht, das es einem Vogel noch ermöglichen würde, sich in die Luft zu erheben. Die Flügel dienen stattdessen zur <a href=\"/wiki/Balz\" title=\"Balz\">Balz</a>, zum Schattenspenden und zum Halten des Gleichgewichts beim schnellen Laufen. Als einziger <a href=\"/wiki/Rezent_%28Biologie%29\" title=\"Rezent (Biologie)\">rezenter</a> Vogel besitzt der Strauß an allen drei Fingern <a href=\"/wiki/Kralle\" title=\"Kralle\">Krallen</a>.</p>\r\n"
			+ "<p><i>Siehe auch:</i> <a href=\"/wiki/Vogelskelett\" title=\"Vogelskelett\">Vogelskelett</a></p>\r\n"
			+ "\r\n"
			+ "<p><a name=\"Stimme\" id=\"Stimme\"></a></p>\r\n"
			+ "<h2><span class=\"mw-headline\">Stimme</span></h2>\r\n"
			+ "<p>Zu den typischsten Lautgebungen des Straußes gehört ein Ruf des Männchens, der dem Brüllen eines <a href=\"/wiki/L%C3%B6we\" title=\"Löwe\">Löwen</a> ähnelt. Ein tiefes „bu bu buuuuu huuu“ wird mehrmals wiederholt. Der Laut wird bei der <a href=\"/wiki/Balz\" title=\"Balz\">Balz</a> und beim Austragen von Rangstreitigkeiten ausgestoßen. Daneben sind Strauße beiderlei Geschlechts zu pfeifenden, schnaubenden und knurrenden Lauten in der Lage. Nur junge Straußenküken geben auch melodischere Rufe von sich, die dazu dienen, das Muttertier auf sie aufmerksam zu machen.</p>\r\n"
			+ "<p><a name=\"Verbreitung_und_Lebensraum\" id=\"Verbreitung_und_Lebensraum\"></a></p>\r\n"
			+ "<h2><span class=\"mw-headline\">Verbreitung und Lebensraum</span></h2>\r\n"
			+ "<div class=\"thumb tright\">\r\n"
			+ "<div class=\"thumbinner\" style=\"width:302px;\"><a href=\"/wiki/Bild:Struthio_camelus_Distribution.png\" class=\"internal\" title=\"Verbreitung\"><img src=\"http://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Struthio_camelus_Distribution.png/300px-Struthio_camelus_Distribution.png\" alt=\"Verbreitung\" width=\"300\" height=\"367\" longdesc=\"/wiki/Bild:Struthio_camelus_Distribution.png\" class=\"thumbimage\" /></a>\r\n"
			+ "<div class=\"thumbcaption\">\r\n"
			+ "\r\n"
			+ "<div class=\"magnify\" style=\"float:right\"><a href=\"/wiki/Bild:Struthio_camelus_Distribution.png\" class=\"internal\" title=\"vergrößern\"><img src=\"/skins-1.5/common/images/magnify-clip.png\" width=\"15\" height=\"11\" alt=\"\" /></a></div>\r\n"
			+ "Verbreitung</div>\r\n"
			+ "</div>\r\n"
			+ "</div>\r\n"
			+ "<p>Das natürliche Verbreitungsgebiet des Straußes ist <a href=\"/wiki/Afrika\" title=\"Afrika\">Afrika</a>, insbesondere <a href=\"/wiki/Ostafrika\" title=\"Ostafrika\">Ost-</a> und <a href=\"/wiki/S%C3%BCdafrika\" title=\"Südafrika\">Südafrika</a>. Ausgestorben ist er auf der <a href=\"/wiki/Arabische_Halbinsel\" title=\"Arabische Halbinsel\">Arabischen Halbinsel</a>, in Westasien sowie in Afrika nördlich der Sahara.</p>\r\n"
			+ "<p>Strauße leben in offenen Landschaften wie <a href=\"/wiki/Savanne\" title=\"Savanne\">Savannen</a> und <a href=\"/wiki/W%C3%BCste\" title=\"Wüste\">Wüsten</a>. Bevorzugt werden Habitate mit kurzem Gras und nicht zu hohem Baumbestand. Wo das Gras höher als einen Meter wächst, fehlen Strauße. Gelegentlich dringen sie in Buschland vor, bleiben dort aber nicht lang, da sie an schneller Fortbewegung gehindert werden und dort nicht weit blicken können. Reine Wüsten ohne Vegetation eignen sich auch nicht als ständiger Lebensraum, werden aber auf Wanderungen durchquert. Weil Strauße ihren gesamten Flüssigkeitsbedarf aus der Nahrung beziehen können, benötigen sie keinen Zugang zum Wasser, und lange Trockenperioden sind in der Regel ebenfalls kein Problem für sie.</p>\r\n"
			+ "\r\n"
			+ "<p>In <a href=\"/wiki/Australien\" title=\"Australien\">Australien</a> gibt es einige hundert Strauße, die aus Farmen entlaufen und nun verwildert sind. Natürlich heimisch sind Strauße dort nicht.</p>\r\n"
			+ "<p><a name=\"Lebensweise\" id=\"Lebensweise\"></a></p>\r\n"
			+ "<h2><span class=\"mw-headline\">Lebensweise</span></h2>\r\n"
			+ "<p><a name=\"Aktivit.C3.A4t\" id=\"Aktivit.C3.A4t\"></a></p>\r\n"
			+ "<h3><span class=\"mw-headline\">Aktivität</span></h3>\r\n"
			+ "<div class=\"thumb tright\">\r\n"
			+ "<div class=\"thumbinner\" style=\"width:302px;\"><a href=\"/wiki/Bild:Afrikanischer_strauss.jpg\" class=\"internal\" title=\"Afrikanischer Strauß ♂ im Zoo\"><img src=\"http://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Afrikanischer_strauss.jpg/300px-Afrikanischer_strauss.jpg\" alt=\"Afrikanischer Strauß ♂ im Zoo\" width=\"300\" height=\"400\" longdesc=\"/wiki/Bild:Afrikanischer_strauss.jpg\" class=\"thumbimage\" /></a>\r\n"
			+ "<div class=\"thumbcaption\">\r\n"
			+ "<div class=\"magnify\" style=\"float:right\"><a href=\"/wiki/Bild:Afrikanischer_strauss.jpg\" class=\"internal\" title=\"vergrößern\"><img src=\"/skins-1.5/common/images/magnify-clip.png\" width=\"15\" height=\"11\" alt=\"\" /></a></div>\r\n"
			+ "Afrikanischer Strauß ♂ im Zoo</div>\r\n"
			+ "\r\n"
			+ "</div>\r\n"
			+ "</div>\r\n"
			+ "<p>Strauße sind tagaktive Vögel, die besonders in den Dämmerungsstunden aktiv sind. In Zeiten mit knappem Nahrungsangebot müssen sie allerdings große Wanderungen unternehmen und sind dann auch in der Lage, in der Mittagssonne zu wandern. Nachts ruhen sie, wobei sie für gewöhnlich die Hälse aufrecht, aber die Augen geschlossen halten. Nur für kurzzeitige Tiefschlafphasen werden Hals und Kopf auf das Rückengefieder oder auf den Boden gebettet.</p>\r\n"
			+ "<p><a name=\"Sozialverhalten\" id=\"Sozialverhalten\"></a></p>\r\n"
			+ "<h3><span class=\"mw-headline\">Sozialverhalten</span></h3>\r\n"
			+ "<p>Außerhalb der Brutzeit leben Strauße für gewöhnlich in lockeren Verbänden, die zwei bis fünf, in manchen Gegenden aber auch hundert und mehr Tiere umfassen können. In Wüstengegenden sammeln sich bis zu 680 Tiere um Wasserlöcher. Der Zusammenhalt der Straußenverbände ist locker, denn die Mitglieder der Gruppe kommen und gehen nach Belieben. Oft sieht man auch einzelne Strauße. Trotzdem gibt es innerhalb der Gruppen klare Hierarchien. Rangstreitigkeiten werden meistens durch Drohlaute und Drohgebärden geregelt; dabei werden Flügel und Schwanzfedern aufgestellt und der Hals aufrecht gehalten. Der rangniedrigere Vogel zeigt seine Unterwerfung, indem er den Hals U-förmig biegt und den Kopf nach unten hält; auch Flügel und Schwanz zeigen nach unten. Selten kann eine Rangstreitigkeit auch in einen kurzen Kampf münden.</p>\r\n"
			+ "<p>Zur Fortpflanzungszeit lösen sich diese losen Verbände auf, und geschlechtsreife Männchen beginnen mit dem Sammeln eines <a href=\"/wiki/Harem\" title=\"Harem\">Harems</a>.</p>\r\n"
			+ "<p><a name=\"Ern.C3.A4hrung\" id=\"Ern.C3.A4hrung\"></a></p>\r\n"
			+ "<h3><span class=\"mw-headline\">Ernährung</span></h3>\r\n"
			+ "<p>Strauße sind vorwiegend <a href=\"/wiki/Pflanzenfresser\" title=\"Pflanzenfresser\">Pflanzenfresser</a>, nehmen gelegentlich aber auch <a href=\"/wiki/Insekten\" title=\"Insekten\">Insekten</a> und andere Kleintiere zu sich. Vorwiegend fressen sie Körner, Gräser, Kräuter, Blätter, Blüten und Früchte. Insekten wie Raupen und Heuschrecken sind nur Beikost. Bevorzugt wird Nahrung, die vom Boden aufgepickt werden kann. Nur ausnahmsweise werden Blätter oder Früchte von Sträuchern oder Bäumen aufgelesen. Strauße können ihre Nahrung optimal verwerten, wofür ein 14 Meter langer <a href=\"/wiki/Darm\" title=\"Darm\">Darm</a> sorgt. Um die Zerkleinerung der Nahrung zu fördern, schlucken Strauße Sand und Steine (<a href=\"/wiki/Gastrolith\" title=\"Gastrolith\">Gastrolithen</a>), haben aber die Neigung, alle möglichen kleinen Objekte aufzupicken, die ähnliche Zwecke erfüllen könnten. In Straußenmägen fand man daher schon Münzen, Nägel und ähnliche Gegenstände.</p>\r\n"
			+ "\r\n"
			+ "<p><a name=\"Feinde\" id=\"Feinde\"></a></p>\r\n"
			+ "<h3><span class=\"mw-headline\">Feinde</span></h3>\r\n"
			+ "<div class=\"thumb tright\">\r\n"
			+ "<div class=\"thumbinner\" style=\"width:302px;\"><a href=\"/wiki/Bild:Strau%C3%9Fenfu%C3%9F.jpg\" class=\"internal\" title=\"Der Fuß mit seinen scharfen Krallen ist eine gefährliche Waffe\"><img src=\"http://upload.wikimedia.org/wikipedia/de/thumb/f/f1/Strau%C3%9Fenfu%C3%9F.jpg/300px-Strau%C3%9Fenfu%C3%9F.jpg\" alt=\"Der Fuß mit seinen scharfen Krallen ist eine gefährliche Waffe\" width=\"300\" height=\"225\" longdesc=\"/wiki/Bild:Strau%C3%9Fenfu%C3%9F.jpg\" class=\"thumbimage\" /></a>\r\n"
			+ "<div class=\"thumbcaption\">\r\n"
			+ "<div class=\"magnify\" style=\"float:right\"><a href=\"/wiki/Bild:Strau%C3%9Fenfu%C3%9F.jpg\" class=\"internal\" title=\"vergrößern\"><img src=\"/skins-1.5/common/images/magnify-clip.png\" width=\"15\" height=\"11\" alt=\"\" /></a></div>\r\n"
			+ "Der Fuß mit seinen scharfen Krallen ist eine gefährliche Waffe</div>\r\n"
			+ "</div>\r\n"
			+ "</div>\r\n"
			+ "<p>Die wichtigsten Feinde des Straußes sind <a href=\"/wiki/L%C3%B6we\" title=\"Löwe\">Löwen</a>, <a href=\"/wiki/Leopard\" title=\"Leopard\">Leoparden</a> und <a href=\"/wiki/Gepard\" title=\"Gepard\">Geparden</a>. Indem sich Strauße meistens in Gruppen aufhalten, schützen sie sich durch gemeinsame Beobachtung vor der Gefahr. Dadurch verringert sich für den einzelnen Vogel das Risiko, als Beute auserwählt zu werden; zudem hat jedes Gruppenmitglied mehr Zeit zum Fressen. In den Savannen schließen sich Strauße oft auch den Herden von <a href=\"/wiki/Zebra\" title=\"Zebra\">Zebras</a> und <a href=\"/wiki/Gazellen\" title=\"Gazellen\">Gazellen</a> an, da auch diese Tiere wachsam nach denselben Raubtieren Ausschau halten.</p>\r\n"
			+ "\r\n"
			+ "<p>Ein weit verbreitetes Gerücht besagt, dass der Strauß bei Bedrohung durch Feinde den Kopf in den Sandboden steckt. Tatsächlich rettet sich der Strauß, der eine sehr hohe Laufgeschwindigkeit erreichen kann, meist durch Davonlaufen, er ist aber auch in der Lage, sich mit einem gezielten Tritt zu verteidigen, der einen Löwen oder einen Menschen zu töten vermag. Vor allem brütende Strauße jedoch legen sich bei nahender Gefahr oft auf den Boden und halten Hals und Kopf dabei gerade ausgestreckt. Da aus der Ferne der flach am Boden liegende Hals nicht mehr zu sehen ist, könnte dieses Verhalten zu der Legende geführt haben.</p>\r\n"
			+ "<p><a name=\"Fortpflanzung\" id=\"Fortpflanzung\"></a></p>\r\n"
			+ "<h3><span class=\"mw-headline\">Fortpflanzung</span></h3>\r\n"
			+ "<div class=\"thumb tright\">\r\n"
			+ "<div class=\"thumbinner\" style=\"width:302px;\"><a href=\"/wiki/Bild:Struthio_camelus.jpg\" class=\"internal\" title=\"Straußenpaar mit Küken, Hahn (links), Henne (rechts)\"><img src=\"http://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Struthio_camelus.jpg/300px-Struthio_camelus.jpg\" alt=\"Straußenpaar mit Küken, Hahn (links), Henne (rechts)\" width=\"300\" height=\"214\" longdesc=\"/wiki/Bild:Struthio_camelus.jpg\" class=\"thumbimage\" /></a>\r\n"
			+ "<div class=\"thumbcaption\">\r\n"
			+ "<div class=\"magnify\" style=\"float:right\"><a href=\"/wiki/Bild:Struthio_camelus.jpg\" class=\"internal\" title=\"vergrößern\"><img src=\"/skins-1.5/common/images/magnify-clip.png\" width=\"15\" height=\"11\" alt=\"\" /></a></div>\r\n"
			+ "Straußenpaar mit Küken, Hahn (links), Henne (rechts)</div>\r\n"
			+ "</div>\r\n"
			+ "</div>\r\n"
			+ "<p>Die Paarungszeit ist in unterschiedlichen Regionen Afrikas sehr verschieden. In den Savannen Afrikas fällt sie in die Trockenzeit zwischen Juni und Oktober. In trockeneren Gegenden, zum Beispiel in der Wüste <a href=\"/wiki/Namib\" title=\"Namib\">Namib</a>, dauert die Fortpflanzungszeit hingegen das ganze Jahr an.</p>\r\n"
			+ "\r\n"
			+ "<p>Die Hähne werden in der Paarungszeit territorial. Sie verteidigen dann ein Revier mit einer Fläche zwischen 2 und 15 km². Andere Männchen werden aus dem Revier vertrieben, Weibchen jedoch mit einem Balzritual empfangen.</p>\r\n"
			+ "<p>Obwohl monogame Paare vorkommen, hat in der Regel ein Hahn einen ganzen Harem. Eines der Weibchen ist dabei eindeutig als Haupthenne auszumachen. Daneben gibt es mehrere rangniedrige Weibchen, die so genannten Nebenhennen. Die Haupthenne bleibt mit dem Hahn oft über mehrere Jahre zusammen. Bei den Nebenhennen handelt es sich meistens um recht junge Weibchen.</p>\r\n"
			+ "<p>Der Hahn paart sich zunächst mit der Haupthenne, sodann mit den Nebenhennen. Der Paarung geht ein <a href=\"/wiki/Balz\" title=\"Balz\">Balzritual</a> voraus, bei dem der Hahn seine Flügel präsentiert und sie abwechselnd auf und ab schwingt. Gleichzeitig bläst er seinen farbigen Hals auf und lässt ihn ebenfalls abwechselnd nach links und rechts pendeln. Mit stampfenden Füßen geht der Hahn in dieser Position auf die Henne zu. Das Weibchen zeigt seine Paarungsbereitschaft mit einer Demutsgeste, bei der es den Kopf und die Flügel hängen lässt. Im Anschluss an die Paarung wählt die Haupthenne eine der Nestgruben, die der Hahn zuvor angelegt hat. Dies sind mit den Füßen in die Erde gekratzte Kuhlen mit einem Durchmesser von etwa 3 Metern.</p>\r\n"
			+ "<div class=\"thumb tright\">\r\n"
			+ "<div class=\"thumbinner\" style=\"width:302px;\"><a href=\"/wiki/Bild:Struthio_camelus_-_Strausskueken.jpg\" class=\"internal\" title=\"Küken\"><img src=\"http://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Struthio_camelus_-_Strausskueken.jpg/300px-Struthio_camelus_-_Strausskueken.jpg\" alt=\"Küken\" width=\"300\" height=\"327\" longdesc=\"/wiki/Bild:Struthio_camelus_-_Strausskueken.jpg\" class=\"thumbimage\" /></a>\r\n"
			+ "<div class=\"thumbcaption\">\r\n"
			+ "<div class=\"magnify\" style=\"float:right\"><a href=\"/wiki/Bild:Struthio_camelus_-_Strausskueken.jpg\" class=\"internal\" title=\"vergrößern\"><img src=\"/skins-1.5/common/images/magnify-clip.png\" width=\"15\" height=\"11\" alt=\"\" /></a></div>\r\n"
			+ "Küken</div>\r\n"
			+ "</div>\r\n"
			+ "</div>\r\n"
			+ "\r\n"
			+ "<p>Die Nebenhennen legen ihre Eier in dasselbe Nest wie zuvor die Haupthenne und werden nach dem Legen von der Haupthenne vertrieben. Oft gehen sie nun in das Revier eines anderen Straußenhahns, mit dem sie ebenfalls die Paarung eingehen.</p>\r\n"
			+ "<p>Die Haupthenne legt durchschnittlich acht, selten bis zu zwölf Eier. Hinzu kommen je Nebenhenne zwei bis fünf Eier. In den großen Gemeinschaftsnestern liegen am Ende bis zu achtzig Eier. Die Eier sind glänzend weiß, bis zu 1.900 Gramm schwer und haben einen Durchmesser von 15 Zentimetern, ihr Inhalt entspricht dem von 24 Hühnereiern. Damit zählen sie absolut gesehen zu den größten Eiern der Welt, in Relation zur Körpergröße eines Straußes sind sie jedoch die kleinsten.</p>\r\n"
			+ "<p>Nur das eigentliche Paar verbleibt schließlich am Nest und sorgt gemeinsam für die Brut. Da ein Vogel mit seinem Körper nur maximal zwanzig Eier bedecken kann, entfernt die Haupthenne zuvor die überschüssigen Eier der inzwischen vertriebenen Nebenhennen. In der Mitte des Nestes werden die eigenen Eier platziert, die von der Haupthenne offenbar an Größe und Gewicht zugeordnet werden können. Obwohl die eigenen Eier also bevorzugt werden, ist immer noch Raum für zehn bis fünfzehn Eier von Nebenhennen, die mit ausgebrütet werden. Doch nicht nur die Nebenhennen profitieren von dieser Verhaltensweise: Wird das Gelege von Eierräubern angegriffen, werden mit höherer Wahrscheinlichkeit die außen liegenden Eier der Nebenhennen entführt, was einen zusätzlichen Schutz für die Eier der Haupthenne bedeutet.</p>\r\n"
			+ "<div class=\"thumb tright\">\r\n"
			+ "<div class=\"thumbinner\" style=\"width:302px;\"><a href=\"/wiki/Bild:Straussenei_BMK.jpg\" class=\"internal\" title=\"Straußenei (rechts) im Vergleich zu einem Hühnerei\"><img src=\"http://upload.wikimedia.org/wikipedia/de/thumb/4/45/Straussenei_BMK.jpg/300px-Straussenei_BMK.jpg\" alt=\"Straußenei (rechts) im Vergleich zu einem Hühnerei\" width=\"300\" height=\"225\" longdesc=\"/wiki/Bild:Straussenei_BMK.jpg\" class=\"thumbimage\" /></a>\r\n"
			+ "<div class=\"thumbcaption\">\r\n"
			+ "<div class=\"magnify\" style=\"float:right\"><a href=\"/wiki/Bild:Straussenei_BMK.jpg\" class=\"internal\" title=\"vergrößern\"><img src=\"/skins-1.5/common/images/magnify-clip.png\" width=\"15\" height=\"11\" alt=\"\" /></a></div>\r\n"
			+ "Straußenei (rechts) im Vergleich zu einem Hühnerei</div>\r\n"
			+ "</div>\r\n"
			+ "</div>\r\n"
			+ "<p>Für gewöhnlich werden die Eier bei Tage von der Henne und bei Nacht vom Hahn bebrütet. Zahlreiche Raubtiere versuchen immer wieder, die brütenden Vögel vom Nest fortzulocken, um an die Eier zu gelangen. Dies sind vor allem <a href=\"/wiki/Schakal\" title=\"Schakal\">Schakale</a>, <a href=\"/wiki/Hy%C3%A4nen\" title=\"Hyänen\">Hyänen</a> und <a href=\"/wiki/Schmutzgeier\" title=\"Schmutzgeier\">Schmutzgeier</a>. Letztere öffnen Straußeneier unter Zuhilfenahme eines Steins, den sie auf die Eier fallen lassen. Nur zehn Prozent aller Gelege werden daher erfolgreich ausgebrütet.</p>\r\n"
			+ "\r\n"
			+ "<p>Nach sechs Wochen schlüpfen die Küken. Sie tragen bereits ein hellbraunes Daunenkleid. Die Eltern fahren nun mit der Brutpflege fort, indem sie schützend ihre Flügel über den Jungen ausbreiten, um sie so vor Sonne und Regen zu schützen. Im Alter von nur drei Tagen verlassen die Küken erstmals das Nest und folgen den Eltern nun überall hin. Gelegentlich treffen zwei Straußenpaare aufeinander. Es kommt dann zu Drohgebärden und oft zu Kämpfen, bei denen ein Paar siegreich ist und anschließend die Jungen des unterlegenen Paares übernimmt. Auf diese Weise kann ein starkes Paar etliche Junge anderer Paare um sich sammeln. In einem Fall wurde ein Straußenpaar mit 380 Küken beobachtet. Auch dieses Verhalten führt, wie das Ausbrüten der Eier der Nebenhennen, wiederum dazu, dass bei einem Angriff von Raubtieren mit höherer Wahrscheinlichkeit die fremden und nicht die eigenen Küken betroffen sind.</p>\r\n"
			+ "<p>Mit drei Monaten wechseln die Jungen vom Daunen- zum Jugendkleid. Nach einem Jahr sind sie so groß wie ihre Eltern; nur fünfzehn Prozent der geschlüpften Küken erreichen jedoch dieses Alter. Geschlechtsreif werden weibliche Strauße mit zwei, männliche mit drei bis vier Jahren. Sie haben eine Lebenserwartung von etwa 30 bis 40 Jahren, in <a href=\"/wiki/Zoo\" title=\"Zoo\">Zoos</a> auch von 50 Jahren oder mehr.</p>\r\n"
			+ "<p><a name=\"Stammesgeschichte_und_Systematik\" id=\"Stammesgeschichte_und_Systematik\"></a></p>\r\n"
			+ "<h2><span class=\"mw-headline\">Stammesgeschichte und Systematik</span></h2>\r\n"
			+ "<p>Der Afrikanische Strauß ist die einzige lebende Art der Strauße (Struthionidae), von denen ansonsten nur fossile Arten bekannt sind. Welche andere Familie der <a href=\"/wiki/Laufv%C3%B6gel\" title=\"Laufvögel\">Laufvögel</a> als Schwestergruppe des Straußes ausgemacht werden kann, ist umstritten. Diskutiert werden die erst in jüngerer Zeit ausgestorbenen <a href=\"/wiki/Elefantenv%C3%B6gel\" title=\"Elefantenvögel\">Elefantenvögel</a> <a href=\"/wiki/Madagaskar\" title=\"Madagaskar\">Madagaskars</a> und die <a href=\"/wiki/Nandus\" title=\"Nandus\">Nandus</a>; bei Letzteren besteht bei vielen Zoologen allerdings die Überzeugung, dass sie ihre Ähnlichkeit zum Strauß in <a href=\"/wiki/Konvergente_Evolution\" title=\"Konvergente Evolution\">konvergenter Evolution</a> erworben haben. Eine neuerdings wieder diskutierte Hypothese sieht als Schwestergruppe des Straußes ein gemeinsames <a href=\"/wiki/Taxon\" title=\"Taxon\">Taxon</a> von Nandus und <a href=\"/wiki/Stei%C3%9Fh%C3%BChner\" title=\"Steißhühner\">Steißhühnern</a>. Oft wird der Strauß als basales Taxon an der Wurzel der Laufvögel eingeordnet; hier gibt es jedoch zahlreiche andere Ansätze (Näheres siehe <a href=\"/wiki/Laufv%C3%B6gel\" title=\"Laufvögel\">Laufvögel</a>).</p>\r\n"
			+ "\r\n"
			+ "<p>Fünf Unterarten werden für gewöhnlich unterschieden:</p>\r\n"
			+ "<ul>\r\n"
			+ "<li>Der Nordafrikanische Strauß (<i>Struthio camelus camelus</i>) lebt in den Savannen Westafrikas und ist über die <a href=\"/wiki/Sahelzone\" title=\"Sahelzone\">Sahelzone</a> bis ins westliche <a href=\"/wiki/%C3%84thiopien\" title=\"Äthiopien\">Äthiopien</a> verbreitet; nördlich der Sahara ist er ausgestorben.</li>\r\n"
			+ "<li>Der Somali-Strauß (<i>Struthio camelus molybdophanes</i>) besiedelt <a href=\"/wiki/Somalia\" title=\"Somalia\">Somalia</a> und das östliche Äthiopien.</li>\r\n"
			+ "\r\n"
			+ "<li>Der Massai-Strauß (<i>Struthio camelus massaicus</i>) lebt in <a href=\"/wiki/Kenia\" title=\"Kenia\">Kenia</a> und <a href=\"/wiki/Tansania\" title=\"Tansania\">Tansania</a>.</li>\r\n"
			+ "<li>Der Südafrikanische Strauß (<i>Struthio camelus australis</i>) findet sich dagegen im südlichen Afrika.</li>\r\n"
			+ "<li>Der heute ausgestorbene Arabische Strauß (<i>Struthio camelus syriacus</i>) lebte einst in Westasien.</li>\r\n"
			+ "\r\n"
			+ "</ul>\r\n"
			+ "<p>Populationen der <a href=\"/wiki/Westsahara\" title=\"Westsahara\">Westsahara</a> wurden bisweilen als sechste Unterart abgetrennt, die dann Zwergstrauß (<i>Struthio camelus spatzi</i>) genannt wurde. Sie sind im Schnitt kleiner, und ihre Eierschalen haben eine andere Struktur. Von der Fachwelt wird diese Unterart allerdings größtenteils abgelehnt. Ebenfalls angezweifelt wird die aufgrund von DNA-Analysen gelegentlich vorgenommene Abtrennung des Somali-Straußes als eigenständige Art (<i>Struthio molybdophanes</i>).</p>\r\n"
			+ "<p>Unterschieden sind die einzelnen Unterarten vor allem durch die Farben der Hautpartien von Hals und Beinen der Hähne. Die Hennen der Unterarten sind dagegen kaum voneinander zu unterscheiden. Hals und Beine sind beim Nordafrikanischen Strauß, beim Massaistrauß und beim Südafrikanischen Strauß rosafarben, beim Somali-Strauß blaugrau. Die Intensität des Rosatons ist bei jeder Unterart verschieden. Der Nordafrikanische Strauß hat zudem einen Halsring aus weißen Federn, etwas weniger stark ausgeprägt findet man diesen auch beim Massai-Strauß; er fehlt aber beim Somali-Strauß und beim Südafrikanischen Strauß.</p>\r\n"
			+ "<p><a name=\"Fossilgeschichte\" id=\"Fossilgeschichte\"></a></p>\r\n"
			+ "<h3><span class=\"mw-headline\">Fossilgeschichte</span></h3>\r\n"
			+ "<p>Der Ursprung der Familie der Straußenvögel ist rätselhaft. Als ältester Vertreter gilt manchen Fachleuten der so genannte Urstrauß <i>Palaeotis weigelti</i>, dessen Fossilien aus dem <a href=\"/wiki/Eoz%C3%A4n\" title=\"Eozän\">Eozän</a> in der <a href=\"/wiki/Grube_Messel\" title=\"Grube Messel\">Grube Messel</a> und im <a href=\"/wiki/Geiseltal\" title=\"Geiseltal\">Geiseltal</a> gefunden wurden. Dieses Tier zeigt aber nach neuen Erkenntnissen noch mehr Ähnlichkeiten mit den <a href=\"/wiki/Nandus\" title=\"Nandus\">Nandus</a> und könnte daher passender als „Urnandu“ benannt werden.</p>\r\n"
			+ "\r\n"
			+ "<p>Vögel, die unbestritten zu den Straußen gehören, sind seit dem <a href=\"/wiki/Mioz%C3%A4n\" title=\"Miozän\">Miozän</a> belegt. Damit ist <i>Struthio</i> eine sehr alte Vogelgattung. <i>Struthio orlovi</i> aus dem Miozän <a href=\"/wiki/Moldawien\" title=\"Moldawien\">Moldawiens</a> ist die älteste bekannte Art. Im <a href=\"/wiki/Plioz%C3%A4n\" title=\"Pliozän\">Pliozän</a> lebten mehrere Arten in Asien, beispielsweise in der <a href=\"/wiki/Mongolei\" title=\"Mongolei\">Mongolei</a> und in <a href=\"/wiki/China\" title=\"China\">China</a> (<i>Struthio chersonensis</i>, <i>Struthio mongolicus</i>, <i>Struthio wimani</i>). Der Asiatische Strauß (<i>Struthio asiaticus</i>) lebte im <a href=\"/wiki/Pleistoz%C3%A4n\" title=\"Pleistozän\">Pleistozän</a> in den Steppen Zentralasiens. Im Pleistozän tauchte auch der heute lebende Afrikanische Strauß auf, dessen Verbreitungsgebiet während der letzten Eiszeit auch <a href=\"/wiki/Spanien\" title=\"Spanien\">Spanien</a> und <a href=\"/wiki/Indien\" title=\"Indien\">Indien</a> umfasste.</p>\r\n"
			+ "\r\n"
			+ "<p><a name=\"Strau.C3.9F_und_Mensch\" id=\"Strau.C3.9F_und_Mensch\"></a></p>\r\n"
			+ "<h2><span class=\"mw-headline\">Strauß und Mensch</span></h2>\r\n"
			+ "<div class=\"thumb tright\">\r\n"
			+ "<div class=\"thumbinner\" style=\"width:282px;\"><a href=\"/wiki/Bild:OstrichCartJacksonville1.jpg\" class=\"internal\" title=\"Der Strauß als Zugtier (Florida 1910)\"><img src=\"http://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/OstrichCartJacksonville1.jpg/280px-OstrichCartJacksonville1.jpg\" alt=\"Der Strauß als Zugtier (Florida 1910)\" width=\"280\" height=\"174\" longdesc=\"/wiki/Bild:OstrichCartJacksonville1.jpg\" class=\"thumbimage\" /></a>\r\n"
			+ "<div class=\"thumbcaption\">\r\n"
			+ "<div class=\"magnify\" style=\"float:right\"><a href=\"/wiki/Bild:OstrichCartJacksonville1.jpg\" class=\"internal\" title=\"vergrößern\"><img src=\"/skins-1.5/common/images/magnify-clip.png\" width=\"15\" height=\"11\" alt=\"\" /></a></div>\r\n"
			+ "Der Strauß als Zugtier (Florida 1910)</div>\r\n"
			+ "</div>\r\n"
			+ "</div>\r\n"
			+ "<div class=\"thumb tright\">\r\n"
			+ "<div class=\"thumbinner\" style=\"width:282px;\"><a href=\"/wiki/Bild:Neugierige_strausse.jpg\" class=\"internal\" title=\"Neugierige Zuchtstrauße auf einer Farm in Baden-Württemberg\"><img src=\"http://upload.wikimedia.org/wikipedia/de/thumb/2/22/Neugierige_strausse.jpg/280px-Neugierige_strausse.jpg\" alt=\"Neugierige Zuchtstrauße auf einer Farm in Baden-Württemberg\" width=\"280\" height=\"210\" longdesc=\"/wiki/Bild:Neugierige_strausse.jpg\" class=\"thumbimage\" /></a>\r\n"
			+ "<div class=\"thumbcaption\">\r\n"
			+ "<div class=\"magnify\" style=\"float:right\"><a href=\"/wiki/Bild:Neugierige_strausse.jpg\" class=\"internal\" title=\"vergrößern\"><img src=\"/skins-1.5/common/images/magnify-clip.png\" width=\"15\" height=\"11\" alt=\"\" /></a></div>\r\n"
			+ "Neugierige Zuchtstrauße auf einer Farm in <a href=\"/wiki/Baden-W%C3%BCrttemberg\" title=\"Baden-Württemberg\">Baden-Württemberg</a></div>\r\n"
			+ "\r\n"
			+ "</div>\r\n"
			+ "</div>\r\n"
			+ "<p>Die Beziehung des Menschen zum Strauß währt seit wenigstens 5000 Jahren. Sowohl <a href=\"/wiki/%C3%84gypten\" title=\"Ägypten\">altägyptische</a> als auch <a href=\"/wiki/Mesopotamien\" title=\"Mesopotamien\">mesopotamische</a> Kunst zeigen, dass Straußenfedern bereits im frühen Altertum als Schmuck genutzt wurden. Eine Besonderheit der großen, wallenden Federn ist ihre Symmetrie: Die Fahnen beiderseits vom Schaft sind gleich breit. Aus diesem Grund galten sie im alten Ägypten als Sinnbild für Gerechtigkeit.</p>\r\n"
			+ "<p>Noch weiter geht die Beziehung in vielen Regionen Schwarzafrikas, wo Strauße Eingang in Rituale, Märchen und Fabeln gefunden haben. Einen praktischen Nutzen haben die Eier für die <a href=\"/wiki/Khoisan\" title=\"Khoisan\">Khoisan</a>, die sie als Trinkgefäße verwenden oder Halsbänder und Armreife aus den Schalen fertigen.</p>\r\n"
			+ "<p>Erst als im 18. Jahrhundert Straußenfedern als Hutschmuck der reichen Damenwelt Europas in Mode kamen, begann die Jagd auf die Vögel solche Ausmaße anzunehmen, dass sie den Bestand der Art bedrohte. In Westasien, Nordafrika und Südafrika wurde der Strauß restlos ausgerottet. Erst im 19. Jahrhundert begann man, Strauße in Farmen zu züchten, da frei lebende Strauße extrem selten geworden waren. Die erste dieser Farmen entstand 1838 in Südafrika. In der zweiten Hälfte des 20. Jahrhunderts wurden immer mehr Straußenfarmen auch in Europa und Nordamerika eröffnet.</p>\r\n"
			+ "<p>Heute spielen die Federn in der Straußenzucht kaum noch eine Rolle. Man züchtet die Strauße nun vor allem wegen ihres Fleisches und der graublauen Haut, aus der man Leder herstellt. Das Fleisch des Straußes hat einen ganz eigenen Geschmack, der am ehesten mit <a href=\"/wiki/Rindfleisch\" title=\"Rindfleisch\">Rindfleisch</a> oder dem des <a href=\"/wiki/Bison\" title=\"Bison\">Bison</a> zu vergleichen ist. Es ist außerdem cholesterinarm.</p>\r\n"
			+ "\r\n"
			+ "<p>Ein anderer Aspekt der Straußenzucht ist die <a href=\"/wiki/Bakteriostatisch\" title=\"Bakteriostatisch\">bakteriostatische</a>, hypoallergische und entzündungshemmende Wirkung des Straußenfetts. Es enthält einen hohen Anteil an mehrfach ungesättigten Fettsäuren, die der Haut Feuchtigkeit spenden und so für Patienten mit <a href=\"/wiki/Schuppenflechte\" title=\"Schuppenflechte\">Schuppenflechte</a>, <a href=\"/wiki/Neurodermitis\" title=\"Neurodermitis\">Neurodermitis</a> und <a href=\"/wiki/Akne\" title=\"Akne\">Akne</a> geeignet sind. Schon seit Jahrhunderten behandeln die Menschen in Afrika <a href=\"/wiki/Arthritis\" title=\"Arthritis\">Arthritis</a>, Wunden und Geschwüre mit Straußenfett. In den USA, Australien und Südafrika wird es wiederum zur Behandlung von Muskelschmerzen und Gelenkentzündungen angewandt.</p>\r\n"
			+ "<p>Als <a href=\"/wiki/Reittier\" title=\"Reittier\">Reit-</a> und <a href=\"/wiki/Zugtier\" title=\"Zugtier\">Zugtiere</a> werden Strauße erst in jüngerer Zeit als Touristenattraktion genutzt. Dies hat jedoch nirgendwo eine kulturelle Tradition.</p>\r\n"
			+ "\r\n"
			+ "<p>Der Umgang mit Straußen ist nicht ungefährlich. Vor allem die Hähne sind während der Brutzeit angriffslustig. Eindringlinge werden dabei mit Fußtritten traktiert. Die Wucht und vor allem die scharfen Krallen können dabei zu schweren Verletzungen oder gar zum Tode führen.</p>\r\n"
			+ "<p>Der Arabische Strauß wurde am Anfang des 20. Jahrhunderts ausgerottet. Diese Unterart war in Palästina und Syrien noch bis zum Ersten Weltkrieg recht häufig, wurde dann aber durch motorisierte Jagden mit Schusswaffen vernichtet. Das letzte wild lebende Exemplar starb 1966 in <a href=\"/wiki/Jordanien\" title=\"Jordanien\">Jordanien</a>. 1973 setzte man Strauße in der Wüste <a href=\"/wiki/Negev\" title=\"Negev\">Negev</a> in <a href=\"/wiki/Israel\" title=\"Israel\">Israel</a> frei, wodurch sie inzwischen dort wieder heimisch sind. Es handelt sich jedoch um Nordafrikanische Strauße, also eine andere Unterart.</p>\r\n"
			+ "<p>Die Art insgesamt ist nicht bedroht, da sie vor allem in Ostafrika noch häufig ist. Regional ist der Strauß jedoch selten, so in Westafrika und im Südwesten Afrikas.</p>\r\n"
			+ "<p><a name=\"Etymologie\" id=\"Etymologie\"></a></p>\r\n"
			+ "<h2><span class=\"mw-headline\">Etymologie</span></h2>\r\n"
			+ "\r\n"
			+ "<p>Das Wort „Strauß“ stammt vom <a href=\"/wiki/Altgriechische_Sprache\" title=\"Altgriechische Sprache\">altgriechischen</a> στρουθιων (<i>strouthion</i>), was soviel wie „großer Spatz“ bedeutet. Die Griechen bezeichneten den Strauß auch als „Kamelspatz“, was den wissenschaftlichen Namen der Art, <i>Struthio camelus</i>, erklärt.</p>\r\n"
			+ "<p>Auffallend ist, dass der Strauß in verschiedenen Sprachen den verdeutlichenden Zusatz „Vogel“ trägt. Dem deutschen „Vogel Strauß“ entspricht so der niederländische <i>struisvogel</i> und der schwedische <i>fågeln struts</i>. Die englische Bezeichnung <i>ostrich</i>, das französische <i>autruche</i> und das spanische <i>avestruz</i> gehen alle gleichermaßen auf das lateinische <i>avis struthio</i> zurück – <i>avis</i> bedeutet ebenfalls nichts anderes als „Vogel“.</p>\r\n"
			+ "\r\n"
			+ "<p><a name=\"Literatur\" id=\"Literatur\"></a></p>\r\n"
			+ "<h2><span class=\"mw-headline\">Literatur</span></h2>\r\n"
			+ "<ul>\r\n"
			+ "<li>J. O. Horbanczuk: <i>Der Strauß und seine Zucht</i>. Edition Baronigg 2002, <a href=\"http://sapp.telepac.pt/alqueva/straussenbuch.htm\" class=\"external autonumber\" title=\"http://sapp.telepac.pt/alqueva/straussenbuch.htm\" rel=\"nofollow\">[1]</a></li>\r\n"
			+ "<li>Josep del Hoyo et al.: <i>Handbook of the Birds of the World</i>, Band 1 (<i>Ostrich to Ducks</i>). Lynx Edicions 1992, <a href=\"/w/index.php?title=Spezial:ISBN-Suche&amp;isbn=8487334105\" class=\"internal\">ISBN 8487334105</a></li>\r\n"
			+ "<li>Stephen J. Davies: <i>Ratites and Tinamous</i>. Oxford University Press, 2002, <a href=\"/w/index.php?title=Spezial:ISBN-Suche&amp;isbn=0198549962\" class=\"internal\">ISBN 0198549962</a></li>\r\n"
			+ "\r\n"
			+ "</ul>\r\n"
			+ "<p><a name=\"Weblinks\" id=\"Weblinks\"></a></p>\r\n"
			+ "<h2><span class=\"mw-headline\">Weblinks</span></h2>\r\n"
			+ "<div>\r\n"
			+ "<table border=\"0\" cellspacing=\"1\" style=\"background-color:transparent;position:relative\">\r\n"
			+ "<tr valign=\"middle\">\r\n"
			+ "<td><map name=\"ImageMap_1\" id=\"ImageMap_1\">\r\n"
			+ "<area href=\"http://commons.wikimedia.org/wiki/Hauptseite\" shape=\"rect\" coords=\"0,0,0,0\" alt=\"commons:Hauptseite\" title=\"commons:Hauptseite\" /></map>\r\n"
			+ "<div style=\"position: relative;\"><a href=\"http://commons.wikimedia.org/wiki/Hauptseite\" title=\"commons:Hauptseite\"><img src=\"http://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Commons-logo.svg/12px-Commons-logo.svg.png\" alt=\"Commons\" width=\"12\" height=\"16\" longdesc=\"/wiki/Bild:Commons-logo.svg\" usemap=\"#ImageMap_1\" /></a></div>\r\n"
			+ "</td>\r\n"
			+ "<td align=\"left\"><b><span class=\"plainlinks\"><a href=\"http://commons.wikimedia.org/wiki/Struthio_camelus?uselang=de\" class=\"external text\" title=\"http://commons.wikimedia.org/wiki/Struthio_camelus?uselang=de\" rel=\"nofollow\">Commons: afrikanischer Strauß</a></span></b> – Bilder, Videos und/oder Audiodateien</td>\r\n"
			+ "</tr>\r\n"
			+ "</table>\r\n"
			+ "\r\n"
			+ "</div>\r\n"
			+ "<div>\r\n"
			+ "<table border=\"0\" cellspacing=\"1\" style=\"background-color:transparent; position:relative\">\r\n"
			+ "<tr valign=\"middle\">\r\n"
			+ "<td><map name=\"ImageMap_2\" id=\"ImageMap_2\">\r\n"
			+ "<area href=\"http://de.wiktionary.org/wiki/\" shape=\"rect\" coords=\"0,0,0,0\" alt=\"wikt:\" title=\"wikt:\" /></map>\r\n"
			+ "<div style=\"position: relative;\"><a href=\"http://de.wiktionary.org/wiki/\" title=\"wikt:\"><img src=\"http://upload.wikimedia.org/wikipedia/commons/3/38/Wiktionary-ico-de.png\" alt=\"Wiktionary\" width=\"16\" height=\"17\" longdesc=\"/wiki/Bild:Wiktionary-ico-de.png\" usemap=\"#ImageMap_2\" /></a></div>\r\n"
			+ "</td>\r\n"
			+ "<td align=\"left\"><b><a href=\"http://de.wiktionary.org/wiki/Strau%C3%9F\" class=\"extiw\" title=\"wikt:Strauß\">Wiktionary: Strauß</a></b> – Bedeutungserklärungen, Wortherkunft, Synonyme und Übersetzungen</td>\r\n"
			+ "</tr>\r\n"
			+ "</table>\r\n"
			+ "</div>\r\n"
			+ "<ul>\r\n"
			+ "<li><i><a href=\"http://www.redlist.org/search/details.php?species=46918\" class=\"external text\" title=\"http://www.redlist.org/search/details.php?species=46918\" rel=\"nofollow\">Struthio camelus</a></i> in der Roten Liste gefährdeter Arten der IUCN 2006. Eingestellt von: BirdLife International, 2004. Version vom 11. Mai 2006</li>\r\n"
			+ "\r\n"
			+ "</ul>\r\n"
			+ "<p><br /></p>\r\n"
			+ "<div id=\"artikelstadium\"><map name=\"ImageMap_3\" id=\"ImageMap_3\">\r\n"
			+ "<area href=\"/wiki/Wikipedia:Exzellente_Artikel\" shape=\"rect\" coords=\"0,0,0,0\" alt=\"Wikipedia:Exzellente Artikel\" title=\"Wikipedia:Exzellente Artikel\" /></map>\r\n"
			+ "<div style=\"position: relative;\"><a href=\"/wiki/Wikipedia:Exzellente_Artikel\" title=\"Wikipedia:Exzellente Artikel\"><img src=\"http://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Qsicon_exzellent.png/15px-Qsicon_exzellent.png\" alt=\"Exzellente Artikel\" width=\"15\" height=\"15\" longdesc=\"/wiki/Bild:Qsicon_exzellent.png\" usemap=\"#ImageMap_3\" /></a></div>\r\n"
			+ "</div>\r\n"
			+ "<div id=\"Vorlage_Exzellent\">\r\n"
			+ "<table cellspacing=\"8\" cellpadding=\"0\" class=\"hintergrundfarbe1 rahmenfarbe1\" style=\"width: 100%; font-size: 95%; border-top-style: solid; margin-top: 1em; clear: both; position:relative;\">\r\n"
			+ "<tr>\r\n"
			+ "<td style=\"width: 24px; vertical-align: top\"><map name=\"ImageMap_4\" id=\"ImageMap_4\">\r\n"
			+ "<area href=\"/wiki/Wikipedia:Exzellente_Artikel\" shape=\"rect\" coords=\"0,0,0,0\" alt=\"Wikipedia:Exzellente Artikel\" title=\"Wikipedia:Exzellente Artikel\" /></map>\r\n"
			+ "<div style=\"position: relative;\"><a href=\"/wiki/Wikipedia:Exzellente_Artikel\" title=\"Wikipedia:Exzellente Artikel\"><img src=\"http://upload.wikimedia.org/wikipedia/commons/1/10/Qsicon_exzellent.png\" alt=\"Exzellente Artikel\" width=\"24\" height=\"24\" longdesc=\"/wiki/Bild:Qsicon_exzellent.png\" usemap=\"#ImageMap_4\" /></a></div>\r\n"
			+ "</td>\r\n"
			+ "<td>Dieser Artikel wurde in die Liste <a href=\"/wiki/Wikipedia:Exzellente_Artikel\" title=\"Wikipedia:Exzellente Artikel\">exzellenter Artikel</a> aufgenommen.</td>\r\n"
			+ "\r\n"
			+ "</tr>\r\n"
			+ "</table>\r\n"
			+ "</div>\r\n"
			+ "\r\n"
			+ "<!-- \r\n"
			+ "Pre-expand include size: 6087 bytes\r\n"
			+ "Post-expand include size: 1900 bytes\r\n"
			+ "Template argument size: 133 bytes\r\n"
			+ "Maximum: 2048000 bytes\r\n"
			+ "-->\r\n"
			+ "\r\n"
			+ "<!-- Saved in parser cache with key dewiki:pcache:idhash:4786-0!1!0!!de!2!edit=0 and timestamp 20070215150154 -->\r\n"
			+ "<div class=\"printfooter\">\r\n"
			+ "Von „<a href=\"http://de.wikipedia.org/wiki/Afrikanischer_Strau%C3%9F\">http://de.wikipedia.org/wiki/Afrikanischer_Strau%C3%9F</a>“</div>\r\n"
			+ "			<div id=\"catlinks\"><p class=\'catlinks\'><a href=\"/wiki/Spezial:Categories\" title=\"Spezial:Categories\">Kategorien</a>: <span dir=\'ltr\'><a href=\"/wiki/Kategorie:Exzellent\" title=\"Kategorie:Exzellent\">Exzellent</a></span> | <span dir=\'ltr\'><a href=\"/wiki/Kategorie:Laufv%C3%B6gel\" title=\"Kategorie:Laufvögel\">Laufvögel</a></span></p></div>			<!-- end content -->\r\n"
			+ "\r\n"
			+ "			<div class=\"visualClear\"></div>\r\n"
			+ "		</div>\r\n"
			+ "	</div>\r\n"
			+ "		</div>\r\n"
			+ "		<div id=\"column-one\">\r\n"
			+ "	<div id=\"p-cactions\" class=\"portlet\">\r\n"
			+ "		<h5>Diese Seite</h5>\r\n"
			+ "		<div class=\"pBody\">\r\n"
			+ "\r\n"
			+ "			<ul>\r\n"
			+ "					 <li id=\"ca-nstab-main\" class=\"selected\"><a href=\"/wiki/Afrikanischer_Strau%C3%9F\" title=\"Seiteninhalt anzeigen [c]\" accesskey=\"c\">Artikel</a></li>\r\n"
			+ "					 <li id=\"ca-talk\"><a href=\"/wiki/Diskussion:Afrikanischer_Strau%C3%9F\" title=\"Diskussion zum Seiteninhalt [t]\" accesskey=\"t\">Diskussion</a></li>\r\n"
			+ "					 <li id=\"ca-viewsource\"><a href=\"/w/index.php?title=Afrikanischer_Strau%C3%9F&amp;action=edit\" title=\"Diese Seite ist geschützt. Der Quelltext kann angesehen werden. [e]\" accesskey=\"e\">Quelltext betrachten</a></li>\r\n"
			+ "					 <li id=\"ca-history\"><a href=\"/w/index.php?title=Afrikanischer_Strau%C3%9F&amp;action=history\" title=\"Frühere Versionen dieser Seite [h]\" accesskey=\"h\">Versionen/Autoren</a></li>\r\n"
			+ "				</ul>\r\n"
			+ "		</div>\r\n"
			+ "\r\n"
			+ "	</div>\r\n"
			+ "	<div class=\"portlet\" id=\"p-personal\">\r\n"
			+ "		<h5>Persönliche Werkzeuge</h5>\r\n"
			+ "		<div class=\"pBody\">\r\n"
			+ "			<ul>\r\n"
			+ "				<li id=\"pt-login\"><a href=\"/w/index.php?title=Spezial:Anmelden&amp;returnto=Afrikanischer_Strau%C3%9F\" title=\"Sich einzuloggen wird zwar gerne gesehen, ist aber keine Pflicht. [o]\" accesskey=\"o\">Anmelden</a></li>\r\n"
			+ "			</ul>\r\n"
			+ "		</div>\r\n"
			+ "\r\n"
			+ "	</div>\r\n"
			+ "	<div class=\"portlet\" id=\"p-logo\">\r\n"
			+ "		<a style=\"background-image: url(http://upload.wikimedia.org/wikipedia/de/b/bc/Wiki.png);\" href=\"/wiki/Hauptseite\" title=\"Hauptseite anzeigen [z]\" accesskey=\"z\"></a>\r\n"
			+ "	</div>\r\n"
			+ "	<script type=\"text/javascript\"> if (window.isMSIE55) fixalpha(); </script>\r\n"
			+ "		<div class=\'portlet\' id=\'p-navigation\'>\r\n"
			+ "		<h5>Navigation</h5>\r\n"
			+ "		<div class=\'pBody\'>\r\n"
			+ "\r\n"
			+ "			<ul>\r\n"
			+ "				<li id=\"n-mainpage\"><a href=\"/wiki/Hauptseite\" title=\"Hauptseite anzeigen [z]\" accesskey=\"z\">Hauptseite</a></li>\r\n"
			+ "				<li id=\"n-aboutsite\"><a href=\"/wiki/Wikipedia:%C3%9Cber_Wikipedia\">Über Wikipedia</a></li>\r\n"
			+ "				<li id=\"n-topics\"><a href=\"/wiki/Portal:Wikipedia_nach_Themen\">Themenportale</a></li>\r\n"
			+ "				<li id=\"n-alphindex\"><a href=\"/wiki/Spezial:Alle_Seiten\">Von A bis Z</a></li>\r\n"
			+ "				<li id=\"n-randompage\"><a href=\"/wiki/Spezial:Zuf%C3%A4llige_Seite\" title=\"Zufällige Seite [x]\" accesskey=\"x\">Zufälliger Artikel</a></li>\r\n"
			+ "\r\n"
			+ "			</ul>\r\n"
			+ "		</div>\r\n"
			+ "	</div>\r\n"
			+ "		<div class=\'portlet\' id=\'p-Mitmachen\'>\r\n"
			+ "		<h5>Mitmachen</h5>\r\n"
			+ "		<div class=\'pBody\'>\r\n"
			+ "			<ul>\r\n"
			+ "				<li id=\"n-help\"><a href=\"/wiki/Wikipedia:Hilfe\" title=\"Hilfeseite anzeigen\">Hilfe</a></li>\r\n"
			+ "\r\n"
			+ "				<li id=\"n-portal\"><a href=\"/wiki/Wikipedia:Autorenportal\" title=\"Über das Portal, was Sie tun können, wo was zu finden ist\">Autorenportal</a></li>\r\n"
			+ "				<li id=\"n-recentchanges\"><a href=\"/wiki/Spezial:Letzte_%C3%84nderungen\" title=\"Liste der letzten Änderungen in Wikipedia. [r]\" accesskey=\"r\">Letzte Änderungen</a></li>\r\n"
			+ "				<li id=\"n-sitesupport\"><a href=\"http://wikimediafoundation.org/wiki/Spenden\" title=\"Unterstützen Sie uns\">Spenden</a></li>\r\n"
			+ "			</ul>\r\n"
			+ "		</div>\r\n"
			+ "	</div>\r\n"
			+ "		<div id=\"p-search\" class=\"portlet\">\r\n"
			+ "\r\n"
			+ "		<h5><label for=\"searchInput\">Suche</label></h5>\r\n"
			+ "		<div id=\"searchBody\" class=\"pBody\">\r\n"
			+ "			<form action=\"/wiki/Spezial:Suche\" id=\"searchform\"><div>\r\n"
			+ "				<input id=\"searchInput\" name=\"search\" type=\"text\" title=\"Durchsuche die Wikipedia [f]\" accesskey=\"f\" value=\"\" />\r\n"
			+ "				<input type=\'submit\' name=\"go\" class=\"searchButton\" id=\"searchGoButton\"	value=\"Artikel\" />&nbsp;\r\n"
			+ "				<input type=\'submit\' name=\"fulltext\" class=\"searchButton\" id=\"mw-searchButton\" value=\"Volltext\" />\r\n"
			+ "			</div></form>\r\n"
			+ "		</div>\r\n"
			+ "\r\n"
			+ "	</div>\r\n"
			+ "	<div class=\"portlet\" id=\"p-tb\">\r\n"
			+ "		<h5>Werkzeuge</h5>\r\n"
			+ "		<div class=\"pBody\">\r\n"
			+ "			<ul>\r\n"
			+ "				<li id=\"t-whatlinkshere\"><a href=\"/wiki/Spezial:Verweisliste/Afrikanischer_Strau%C3%9F\" title=\"Liste aller Seiten, die hierher zeigen [j]\" accesskey=\"j\">Links auf diese Seite</a></li>\r\n"
			+ "				<li id=\"t-recentchangeslinked\"><a href=\"/wiki/Spezial:%C3%84nderungen_an_verlinkten_Seiten/Afrikanischer_Strau%C3%9F\" title=\"Letzte Änderungen an Seiten, die von hier verlinkt sind [k]\" accesskey=\"k\">Änderungen an verlinkten Seiten</a></li>\r\n"
			+ "\r\n"
			+ "<li id=\"t-upload\"><a href=\"/wiki/Spezial:Hochladen\" title=\"Dateien hochladen [u]\" accesskey=\"u\">Hochladen</a></li>\r\n"
			+ "<li id=\"t-specialpages\"><a href=\"/wiki/Spezial:Spezialseiten\" title=\"Liste aller Spezialseiten [q]\" accesskey=\"q\">Spezialseiten</a></li>\r\n"
			+ "				<li id=\"t-print\"><a href=\"/w/index.php?title=Afrikanischer_Strau%C3%9F&amp;printable=yes\">Druckversion</a></li>				<li id=\"t-permalink\"><a href=\"/w/index.php?title=Afrikanischer_Strau%C3%9F&amp;oldid=27853050\">Permanentlink</a></li><li id=\"t-cite\"><a href=\"/w/index.php?title=Spezial:Cite&amp;page=Afrikanischer_Strau%C3%9F&amp;id=27853050\">Artikel zitieren</a></li>			</ul>\r\n"
			+ "		</div>\r\n"
			+ "	</div>\r\n"
			+ "	<div id=\"p-lang\" class=\"portlet\">\r\n"
			+ "\r\n"
			+ "		<h5>Andere Sprachen</h5>\r\n"
			+ "		<div class=\"pBody\">\r\n"
			+ "			<ul>\r\n"
			+ "				<li class=\"interwiki-af\"><a href=\"http://af.wikipedia.org/wiki/Volstruis\">Afrikaans</a></li>\r\n"
			+ "				<li class=\"interwiki-ang\"><a href=\"http://ang.wikipedia.org/wiki/Str%C8%B3ta\">Anglo Saxon</a></li>\r\n"
			+ "				<li class=\"interwiki-ar\"><a href=\"http://ar.wikipedia.org/wiki/%D9%86%D8%B9%D8%A7%D9%85%D8%A9\">العربية</a></li>\r\n"
			+ "				<li class=\"interwiki-bg\"><a href=\"http://bg.wikipedia.org/wiki/%D0%A9%D1%80%D0%B0%D1%83%D1%81\">Български</a></li>\r\n"
			+ "\r\n"
			+ "				<li class=\"interwiki-bn\"><a href=\"http://bn.wikipedia.org/wiki/%E0%A6%89%E0%A6%9F%E0%A6%AA%E0%A6%BE%E0%A6%96%E0%A6%BF\">বাংলা</a></li>\r\n"
			+ "				<li class=\"interwiki-ca\"><a href=\"http://ca.wikipedia.org/wiki/Estru%C3%A7\">Català</a></li>\r\n"
			+ "				<li class=\"interwiki-ceb\"><a href=\"http://ceb.wikipedia.org/wiki/Autruche\">Cebuano</a></li>\r\n"
			+ "				<li class=\"interwiki-cs\"><a href=\"http://cs.wikipedia.org/wiki/P%C5%A1tros_dvouprst%C3%BD\">Česky</a></li>\r\n"
			+ "				<li class=\"interwiki-da\"><a href=\"http://da.wikipedia.org/wiki/Struds\">Dansk</a></li>\r\n"
			+ "				<li class=\"interwiki-en\"><a href=\"http://en.wikipedia.org/wiki/Ostrich\">English</a></li>\r\n"
			+ "\r\n"
			+ "				<li class=\"interwiki-eo\"><a href=\"http://eo.wikipedia.org/wiki/Struto\">Esperanto</a></li>\r\n"
			+ "				<li class=\"interwiki-es\"><a href=\"http://es.wikipedia.org/wiki/Struthio_camelus\">Español</a></li>\r\n"
			+ "				<li class=\"interwiki-fi\"><a href=\"http://fi.wikipedia.org/wiki/Strutsi\">Suomi</a></li>\r\n"
			+ "				<li class=\"interwiki-fr\"><a href=\"http://fr.wikipedia.org/wiki/Autruche\">Français</a></li>\r\n"
			+ "				<li class=\"interwiki-gd\"><a href=\"http://gd.wikipedia.org/wiki/Sruth_%28eun%29\">Gàidhlig</a></li>\r\n"
			+ "				<li class=\"interwiki-he\"><a href=\"http://he.wikipedia.org/wiki/%D7%99%D7%A2%D7%9F\">עברית</a></li>\r\n"
			+ "\r\n"
			+ "				<li class=\"interwiki-hr\"><a href=\"http://hr.wikipedia.org/wiki/Noj\">Hrvatski</a></li>\r\n"
			+ "				<li class=\"interwiki-hu\"><a href=\"http://hu.wikipedia.org/wiki/Strucc\">Magyar</a></li>\r\n"
			+ "				<li class=\"interwiki-id\"><a href=\"http://id.wikipedia.org/wiki/Burung_unta\">Bahasa Indonesia</a></li>\r\n"
			+ "				<li class=\"interwiki-io\"><a href=\"http://io.wikipedia.org/wiki/Strucho\">Ido</a></li>\r\n"
			+ "				<li class=\"interwiki-it\"><a href=\"http://it.wikipedia.org/wiki/Struthio_camelus\">Italiano</a></li>\r\n"
			+ "				<li class=\"interwiki-ja\"><a href=\"http://ja.wikipedia.org/wiki/%E3%83%80%E3%83%81%E3%83%A7%E3%82%A6\">日本語</a></li>\r\n"
			+ "\r\n"
			+ "				<li class=\"interwiki-li\"><a href=\"http://li.wikipedia.org/wiki/Stroes\">Limburgs</a></li>\r\n"
			+ "				<li class=\"interwiki-lt\"><a href=\"http://lt.wikipedia.org/wiki/Afrikinis_strutis\">Lietuvių</a></li>\r\n"
			+ "				<li class=\"interwiki-ms\"><a href=\"http://ms.wikipedia.org/wiki/Burung_Unta\">Bahasa Melayu</a></li>\r\n"
			+ "				<li class=\"interwiki-nl\"><a href=\"http://nl.wikipedia.org/wiki/Struisvogel\">Nederlands</a></li>\r\n"
			+ "				<li class=\"interwiki-pl\"><a href=\"http://pl.wikipedia.org/wiki/Stru%C5%9B\">Polski</a></li>\r\n"
			+ "				<li class=\"interwiki-pt\"><a href=\"http://pt.wikipedia.org/wiki/Avestruz\">Português</a></li>\r\n"
			+ "\r\n"
			+ "				<li class=\"interwiki-ru\"><a href=\"http://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%83%D1%81\">Русский</a></li>\r\n"
			+ "				<li class=\"interwiki-simple\"><a href=\"http://simple.wikipedia.org/wiki/Ostrich\">Simple English</a></li>\r\n"
			+ "				<li class=\"interwiki-sk\"><a href=\"http://sk.wikipedia.org/wiki/P%C5%A1trosovit%C3%A9\">Slovenčina</a></li>\r\n"
			+ "				<li class=\"interwiki-sl\"><a href=\"http://sl.wikipedia.org/wiki/Noj\">Slovenščina</a></li>\r\n"
			+ "				<li class=\"interwiki-sr\"><a href=\"http://sr.wikipedia.org/wiki/%D0%9D%D0%BE%D1%98\">Српски / Srpski</a></li>\r\n"
			+ "				<li class=\"interwiki-sv\"><a href=\"http://sv.wikipedia.org/wiki/Struts\">Svenska</a></li>\r\n"
			+ "\r\n"
			+ "				<li class=\"interwiki-sw\"><a href=\"http://sw.wikipedia.org/wiki/Mbuni\">Kiswahili</a></li>\r\n"
			+ "				<li class=\"interwiki-ta\"><a href=\"http://ta.wikipedia.org/wiki/%E0%AE%A4%E0%AF%80%E0%AE%95%E0%AF%8D%E0%AE%95%E0%AF%8B%E0%AE%B4%E0%AE%BF\">தமிழ்</a></li>\r\n"
			+ "				<li class=\"interwiki-tr\"><a href=\"http://tr.wikipedia.org/wiki/Deve_ku%C5%9Fu\">Türkçe</a></li>\r\n"
			+ "				<li class=\"interwiki-ug\"><a href=\"http://ug.wikipedia.org/wiki/%D8%AA%DB%86%DA%AF%DB%95_%D9%82%DB%87%D8%B4\">Oyghurque</a></li>\r\n"
			+ "				<li class=\"interwiki-vi\"><a href=\"http://vi.wikipedia.org/wiki/%C4%90%C3%A0_%C4%91i%E1%BB%83u\">Tiếng Việt</a></li>\r\n"
			+ "				<li class=\"interwiki-zh\"><a href=\"http://zh.wikipedia.org/wiki/%E9%B8%B5%E9%B8%9F\">中文</a></li>\r\n"
			+ "\r\n"
			+ "			</ul>\r\n"
			+ "		</div>\r\n"
			+ "	</div>\r\n"
			+ "		</div><!-- end of the left (by default at least) column -->\r\n"
			+ "			<div class=\"visualClear\"></div>\r\n"
			+ "			<div id=\"footer\">\r\n"
			+ "				<div id=\"f-poweredbyico\"><a href=\"http://www.mediawiki.org/\"><img src=\"/skins-1.5/common/images/poweredby_mediawiki_88x31.png\" alt=\"Powered by MediaWiki\" /></a></div>\r\n"
			+ "				<div id=\"f-copyrightico\"><a href=\"http://wikimediafoundation.org/\"><img src=\"/images/wikimedia-button.png\" border=\"0\" alt=\"Wikimedia Foundation\"/></a></div>\r\n"
			+ "			<ul id=\"f-list\">\r\n"
			+ "\r\n"
			+ "				<li id=\"lastmod\"> Diese Seite wurde zuletzt am 15. Februar 2007 um 10:58 Uhr geändert.</li>\r\n"
			+ "				<li id=\"copyright\">Ihr Inhalt steht unter der <a class=\'internal\' href=\"/wiki/Wikipedia:GNU_Free_Documentation_License\">GNU-Lizenz für freie Dokumentation</a>.<br />\r\n"
			+ "Wikipedia® ist eine eingetragene Marke der Wikimedia Foundation Inc.<br /></li>\r\n"
			+ "				<li id=\"privacy\"><a href=\"/wiki/Wikipedia:Datenschutz\" title=\"Wikipedia:Datenschutz\">Datenschutz</a></li>\r\n"
			+ "				<li id=\"about\"><a href=\"/wiki/Wikipedia:%C3%9Cber_Wikipedia\" title=\"Wikipedia:Über Wikipedia\">Über Wikipedia</a></li>\r\n"
			+ "\r\n"
			+ "				<li id=\"disclaimer\"><a href=\"/wiki/Wikipedia:Impressum\" title=\"Wikipedia:Impressum\">Impressum</a></li>\r\n"
			+ "			</ul>\r\n"
			+ "		</div>\r\n"
			+ "		\r\n"
			+ "	\r\n"
			+ "		<script type=\"text/javascript\">if (window.runOnloadHook) runOnloadHook();</script>\r\n"
			+ "</div>\r\n" + "";

	public BigHTML2WikipediaTest(String name) {
		super(name);
	}

	public void testBigHTML() {
		HTML2WikiConverter conv = new HTML2WikiConverter();
		conv.setInputHTML(BIG_HTML);
		String result = conv.toWiki(new ToWikipedia());
		System.out.println(result);
	}

}
